fix(op_crates/fetch): uppercase specific methods
denoland/deno pull request #10090
Opened 2021-04-09 15:15 UTC by crowlKats

Closes #10088 
ref: https://fetch.spec.whatwg.org/#methods
> To normalize a method, if it is a byte-case-insensitive match for `DELETE`, `GET`, `HEAD`, `OPTIONS`, `POST`, or `PUT`, byte-uppercase it.

2021-04-09 15:19 UTC, nayeemrmn commented on op_crates/fetch/26_fetch.js
> +      method = method.toUpperCase();
Should be done in Rust IMO.

2021-04-09 15:36 UTC, crowlKats commented on op_crates/fetch/26_fetch.js
> +      method = method.toUpperCase();
done

2021-04-09 15:37 UTC, nayeemrmn approved these changes
LGTM

2021-04-09 15:41 UTC, nayeemrmn requested changes
Actually it needs a test. Fetch against a TCP listener and check that the method is upper cased.

2021-04-11 12:37 UTC, bartlomieju requested changes
Please add a test

2021-04-18 12:23 UTC, lucacasonato commented
Thanks for the effort, but this will be resolved by #10203.

2021-04-18 12:23 UTC, closed without merging