fix: incorrect JSDoc for `Deno.noColor`
denoland/deno pull request #10373
Opened 2021-04-25 22:29 UTC by sno2

2021-04-25 22:46 UTC, kitsonk requested changes
The unrelated formatting changes should be removed from the PR.

2021-04-25 22:47 UTC, lucacasonato reviewed
Revert the unrelated changes please.

2021-04-25 22:47 UTC, lucacasonato commented on cli/dts/lib.deno.ns.d.ts
> +   * initial runtime, then set to true. Otherwise, this is false.
```suggestion
  /** Reflects the `NO_COLOR` environment variable at program start.
```

2021-04-25 22:47 UTC, sno2 commented
> The unrelated formatting changes should be removed from the PR.

I tried fixing them but `deno fmt` kept on doing it.  Should I still revert?

2021-04-25 22:48 UTC, kitsonk commented on cli/dts/lib.deno.ns.d.ts
> +    change: Event;
This needs to be reverted.

2021-04-25 22:49 UTC, lucacasonato commented
Use `./tools/format.ts` instead of `deno fmt`.

2021-04-26 03:57 UTC, kitsonk approved these changes
LGTM

2021-04-26 03:59 UTC, merged