refactor: use primordials in ext/fetch
denoland/deno pull request #11266
Opened 2021-07-04 05:08 UTC by satyarohith

- [x] extensions/fetch/01_fetch_util.js (refactor not required)
- [x] extensions/fetch/20_headers.js
- [x] extensions/fetch/21_formdata.js
- [ ] extensions/fetch/22_body.js
- [ ] extensions/fetch/22_http_client.js
- [ ] extensions/fetch/23_request.js
- [ ] extensions/fetch/23_response.js
- [ ] extensions/fetch/26_fetch.js

Towards https://github.com/denoland/deno/issues/11224

2021-07-04 16:27 UTC, littledivy requested changes
It's fun reviewing these :-)

2021-07-04 16:27 UTC, littledivy commented on extensions/fetch/20_headers.js
>            throw new TypeError(
Line 80 - `TypeError`

2021-07-04 16:27 UTC, littledivy commented on extensions/fetch/20_headers.js
>        throw new TypeError("Header name is not valid.");
ditto

2021-07-04 16:27 UTC, littledivy commented on extensions/fetch/20_headers.js
>        throw new TypeError("Header value is not valid.");
ditto

2021-07-04 16:27 UTC, littledivy commented on extensions/fetch/20_headers.js
>          throw new TypeError("Header name is not valid.");
ditto

2021-07-04 16:27 UTC, littledivy commented on extensions/fetch/20_headers.js
>          throw new TypeError("Header name is not valid.");
ditto ^_^

2021-07-04 16:27 UTC, littledivy commented on extensions/fetch/20_headers.js
>          throw new TypeError("Header name is not valid.");
ditto

2021-07-04 16:27 UTC, littledivy commented on extensions/fetch/20_headers.js
>          throw new TypeError("Header name is not valid.");
ditto

2021-07-04 16:27 UTC, littledivy commented on extensions/fetch/22_body.js
> +  } = window.__bootstrap.primordials;
Add `Uint8Array`

2021-07-04 16:27 UTC, littledivy commented on extensions/fetch/23_request.js
> +    RegExpPrototypeTest,
Add `TypeError`

2021-07-04 16:27 UTC, littledivy commented on extensions/fetch/23_response.js
> +  } = window.__bootstrap.primordials;
Add `TypeError`

2021-07-04 16:52 UTC, SimonRask commented
@satyarohith `01_fetch_util.js` needs `TypeError` added :)

Are you not done since it's a draft?

2021-07-05 20:10 UTC, SimonRask requested changes
`20_headers.js`:
- line 299 `ArrayPrototypeSplice`
- line 403 `SymbolFor`
- line 411 `SymbolToStringTag`
- line 423 `SymbolIterator`

`21_formdata.js`:
- line 70 `SymbolToStringTag`

`22_body.js`:
- line 300 `ArrayPrototypeMap`
- line 340 `ArrayPrototypeSlice`

`23_request.js`:
- line 387 `SymbolToStringTag`
- line 391 `SymbolFor`

`23_response.js`:
- line 370 `SymbolToStringTag`
- line 374 `SymbolFor`

`26_fetch.js`
- line 210 `PromisePrototypeCatch`
- line 220 `PromisePrototypeCatch`
- line 240 `PromisePrototypeCatch`
- line 309 `ArrayPrototypeFilter`
- line 363 `ArrayPrototypePush`
- line 407 `ArrayPrototypePush`
- line 411 `PromisePrototypeThen`
- line 432 `PromisePrototypeCatch`
- line 475 `StringPrototypeToLowerCase`

2021-07-05 20:10 UTC, SimonRask commented on extensions/fetch/23_response.js
> +    TypeError,
`Symbol`

2021-07-05 20:10 UTC, SimonRask commented on extensions/fetch/23_response.js
> +    TypeError,
`RegExp`

2021-07-05 20:10 UTC, SimonRask commented on extensions/fetch/23_response.js
> +    TypeError,
`RangeError`

2021-07-05 20:10 UTC, SimonRask commented on extensions/fetch/26_fetch.js
>            request.headerList.splice(i, 1);
`ArrayPrototypeSplice`

2021-07-06 07:16 UTC, satyarohith commented
Thanks for the thorough review, @SimonRask! :)

2021-07-06 09:32 UTC, bartlomieju approved these changes
LGTM

2021-07-06 09:32 UTC, merged