Revert "feat(cli): enable `useUnknownInCatchVariables` by default"
denoland/deno pull request #12643
Opened 2021-11-03 16:29 UTC by lucacasonato

Over the last few days I have been using this change in canary, and a significant amount of the code I run on a day to day basis broke type checking, and is non trivial to fix. This change is going to cause a lot of pain across the ecosystem, because std is often nested deep in other dependencies (and it also affects many dependencies outside of std, essentially anyone using `try catch`).

I think we should revert this change, and only re-introduce it, and other changes like it until we figure out a solution for this "type errors in dependencies" problem (e.g. #11970).

Reverts denoland/deno#12547

2021-11-03 20:03 UTC, kitsonk requested changes
We should revert the change but not the improved code that guards against errors better.

2021-11-03 21:03 UTC, lucacasonato commented
@kitsonk That sounds very reasonable. I'll prepare a patch tomorrow morning (unless you want to do it).

2021-11-03 21:47 UTC, kitsonk commented
I will try to get to it today.

2021-11-04 00:43 UTC, kitsonk approved these changes
LGTM

2021-11-04 10:30 UTC, merged