Feat(cli) add color flag to deno
denoland/deno pull request #13068
Opened 2021-12-13 13:59 UTC by VishnuJin

this PR adds `--colour` global flag to Deno which can also be set using `DENO_TERM_COLOR` environment variable

Just like `cargo --color` we accept the following 3 arguments 
- auto - the default, this option can identify tty and uses colour only to them
- always - use color even to non-tty
- never - never use colour even in tty

`--color` flag will be overridden by setting `NO_COLOR` environment var

follow up on #13049

2021-12-13 14:03 UTC, VishnuJin commented
@bartlomieju @ry @piscisaureus @kt3k 

please let me know your thoughts on the approach taken or if we need to try something else !!

2021-12-13 14:08 UTC, VishnuJin commented on cli/flags.rs
> +    env::set_var("DENO_TERM_COLOR", preferece.clone());
I'm unsure how reach the `--color` flag's value from `runtime/color.rs` and hence used env var, can this be improved ?

2021-12-14 09:18 UTC, VishnuJin commented
In [test debug jobs](https://github.com/denoland/deno/runs/4515345691?check_suite_focus=true) the colors are used as expected 
In [test release job](https://github.com/denoland/deno/runs/4515345673?check_suite_focus=true) color is not being used despite setting `DENO_TERM_COLOR=always` in CI.yaml not sure why :(

2021-12-14 18:02 UTC, VishnuJin commented
@bartlomieju @ry @piscisaureus @kt3k
this is now working as expected in CI as well

2021-12-14 18:28 UTC, ry requested changes
Hi VishnuJin,

Thanks for the patch but I don't like that our color output has become very complex: NO_COLOR, DENO_TERM_COLOR, --color. This is exposing a lot of complexity to every user to solve a very small issue.

Do the NO_COLOR people suggest a solution to this?

2021-12-14 19:11 UTC, VishnuJin commented
@ry 
I also feel that it would be confusing if we have 2 env vars for almost samething,  as I also mentioned this in [our previous discussion](https://github.com/denoland/deno/pull/13049#issuecomment-991279162) 
But in terms of providing a little bit of more control to the user I think options like `DENO_TERM_COLOR` is handy.

Interestingly [Cargo documentation](https://doc.rust-lang.org/cargo/index.html?search=NO_COLOR) does not have any info on `NO_COLOR` usage If I'm not wrong, as we know it supports [`CARGO_TERM_COLOR`](CARGO_TERM_COLOR) however I guess because of [`termcolor`](https://github.com/BurntSushi/termcolor/search?q=NO_COLOR) dependency `NO_COLOR` becomes valid(has an effect) in cargo

2021-12-15 03:29 UTC, kt3k commented
@VishnuJin 
I think it's not a good idea to change the entire runtime color settings (`use_color` result) based on the environment.

The original issue (#12224) says it's inconvenient to have colors in `console.log`/`console.dir` outputs when the stdout is piped. So I'd suggest we should change only `console` behavior based on tty/no-tty.

The color settings of `console` (`inspect`) is created here https://github.com/denoland/deno/blob/4d176b7b7c11aabc584bee45423f108ea47faefe/ext/console/02_console.js#L1728
Changing this config based on is_tty value should only affect console behaviors.

2021-12-21 13:36 UTC, VishnuJin commented
@kt3k some hints to implement this would help me to proceed further !!

2022-01-24 21:19 UTC, justinmchase commented
I think this is a good feature, 99% of the time you want auto but in those 1% of times, which I've definitely hit both sides it can be extremely frustrating to not have the ability to force colors on or off.

You do definitely hit rare occasions where your OS configuration is just weird or messed up and not specifying tty correctly and thats when you need these switches. It's a fit-and-finish level issue to be sure but this is probably the right way to solve it all things considered.

2022-03-01 09:49 UTC, VishnuJin commented
Closing this PR as it seems to be unnecessary !!

2022-03-01 09:49 UTC, closed without merging