fix(cli/tools/coverage): Split sources by char index
denoland/deno pull request #13114
Opened 2021-12-16 19:54 UTC by nayeemrmn

I think coverage values use char index? Fixes #13111.

2021-12-16 21:09 UTC, bnoordhuis approved these changes
Thanks!

2021-12-16 22:54 UTC, bartlomieju requested changes
I want to get a test case before landing it. I will try to come up with a reproduction for a problem observed in `deno_std`. It seems to involve transpilation and source maps...

2021-12-17 14:43 UTC, bartlomieju commented
I tried this PR against `deno_std` and it indeed fixes the problem; however I'm still having trouble coming up with a test that would reproduce the problem.

2021-12-17 16:17 UTC, bartlomieju approved these changes
I'm going to land this without a test as it fixes the immediate problem. Coverage tools is due to an overhaul anyway and we should address the tests there.

2021-12-17 16:17 UTC, merged