memoryUsage fix
denoland/deno pull request #13293
Opened 2022-01-05 23:20 UTC by R0dn3yS

2022-01-05 23:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno?pullRequest=13293) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno?pullRequest=13293) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno?pullRequest=13293) it.</sub>

2022-01-06 09:31 UTC, bartlomieju requested changes
Thank you for PR @R0dn3yS, can you please add a test to `cli/tests/testdata/workers/test.ts` that verifies that this API is present?

2022-01-09 12:45 UTC, R0dn3yS commented
@bartlomieju PTAL

2022-01-09 15:40 UTC, bartlomieju reviewed
@R0dn3yS nice work, this is almost ready

2022-01-09 15:40 UTC, bartlomieju commented on cli/tests/testdata/workers/test.ts
> +      "data:application/typescript;base64,c2VsZi5vbm1lc3NhZ2UgPSBmdW5jdGlvbigpIHtzZWxmLnBvc3RNZXNzYWdlKERlbm8ubWVtb3J5VXNhZ2UoKSl9",
Please add a comment above that shows original source

2022-01-09 15:40 UTC, bartlomieju commented on cli/tests/testdata/workers/test.ts
> +    console.log(await memoryUsagePromise);
This is error prone, please use assertion function here, that check that received message has all the fields from `Deno.memoryUsage()`

2022-01-09 18:10 UTC, R0dn3yS commented
@bartlomieju should be good now

2022-01-09 22:41 UTC, bartlomieju approved these changes
LGTM, thank you @R0dn3yS

2022-01-09 22:42 UTC, merged