chore: improve build times for `ext/` changes
denoland/deno pull request #13927
Opened 2022-03-12 14:22 UTC by littledivy

`main`:
![Screenshot 2022-03-12 at 7 49 58 PM](https://user-images.githubusercontent.com/34997667/158021625-328eb9e6-d158-4d66-99af-03d10581b416.png)

This PR:
![Screenshot 2022-03-12 at 7 50 28 PM](https://user-images.githubusercontent.com/34997667/158021653-8d2831fa-98e8-43c1-a3a4-f309af8c4ade.png)

Skips running `deno (build.rs)` when it's not needed by removing extension crates as its build dependency.

2022-03-12 23:04 UTC, bartlomieju commented
Looks great, did you verify that snapshots are properly rebuilt when JS code changes in any of the `ext/` crates?

2022-03-13 06:22 UTC, littledivy commented
> Looks great, did you verify that snapshots are properly rebuilt when JS code changes in any of the `ext/` crates?

Yup

2022-03-13 14:47 UTC, bartlomieju requested changes

2022-03-13 14:47 UTC, bartlomieju commented on cli/build.rs
> -  op_crate_libs.insert("deno.web", deno_web::get_declaration());
It seems these `get_declaration` methods could now be removed

2022-03-13 18:11 UTC, bartlomieju approved these changes

2022-03-14 03:38 UTC, merged