feat: add userAgent property to Navigator's prototype
denoland/deno pull request #14415
Opened 2022-04-27 08:51 UTC by randomicon00

PR is related to #14362 

1. Added user_agent field to `BoostrapOptions` struct.
2. Added `userAgent` prototype's property to class Navigator following the same approach as  for `gpu`. 
3. Added `userAgent` variable that gets initialized when `MainWorker::from_bootsrap_options` gets invoked. 
4. Extracted `userAgent`, and renamed to `userAgentInfo` in order to assign it to the navigator's prototype when `mainRuntime` function gets executed.

This is a draft and I didn't include the tests yet. I would like to know if this is the right approach. What makes me doubt is the fact that `WorkerOptions` also contains a `user_agent` field, but I didn't explore if there was a way to get access to it in the JavaScript code. 

I am open to your suggestions. Thank you.

2022-04-27 09:05 UTC, lucacasonato commented
@randomicon00 The approach looks good. I think you can remove the second `user_agent` from `WorkerOptions` (the one outside of `BootstrapOptions`), and update all uses to use `boostrap.user_agent` instead.

2022-04-28 08:53 UTC, randomicon00 commented
@lucacasonato & @bartlomieju sure. Will take into account and apply your suggestions.

2022-05-09 10:21 UTC, bartlomieju commented
@randomicon00 I would love to land this feature for v1.22, which is to be released next week. Do you need any help with the PR?

2022-05-09 10:41 UTC, randomicon00 commented
There is just regression error that was introduced that is blocking me right now. The code used to work. I should be able to make an update by Wednesday.

2022-05-09 11:19 UTC, bartlomieju commented
> There is just a regression error that was introduced that is blocking me right now. The code used to work. I should be able to make an update by Wednesday.

Okay, let me know if you need any help

2022-05-09 20:18 UTC, randomicon00 commented
I did the first part of moving `user_agent` to `BootstrapOptions`. I will write tests in the next commit. Let me know please if there are any specific tasks I need to do on top of that. 
Thank you.

2022-05-09 22:34 UTC, randomicon00 commented
@bartlomieju I have to understand tomorrow why `userAgent`is not defined on `Navigator`causing the test to fail.

2022-05-10 21:14 UTC, randomicon00 commented
Ready to be reviewed. Thanks.

2022-05-10 22:01 UTC, bartlomieju requested changes

2022-05-10 22:01 UTC, bartlomieju commented on cli/main.rs
> +      //user_agent: version::get_user_agent(),
Remove

2022-05-10 22:01 UTC, bartlomieju commented on cli/main.rs
> +    //user_agent: version::get_user_agent(),
Remove

2022-05-10 22:01 UTC, bartlomieju commented on cli/standalone.rs
> +    //user_agent: version::get_user_agent(),
Remove

2022-05-10 22:01 UTC, bartlomieju commented on runtime/examples/hello_runtime.rs
> +    //    user_agent: "hello_runtime".to_string(),
Remove

2022-05-10 22:01 UTC, bartlomieju commented on runtime/web_worker.rs
> +  //pub user_agent: String,
Remove

2022-05-10 22:01 UTC, bartlomieju commented on runtime/worker.rs
> +  //pub user_agent: String,
Remove

2022-05-10 22:01 UTC, bartlomieju commented on runtime/worker.rs
> +      //user_agent: "x".to_string(),
Remove

2022-05-11 19:47 UTC, randomicon00 commented on runtime/worker.rs
> +      //user_agent: "x".to_string(),
Done!

2022-05-12 09:57 UTC, bartlomieju commented on runtime/web_worker.rs
> +  //pub user_agent: String,
@randomicon00 this is still not addressed

2022-05-13 15:52 UTC, bartlomieju approved these changes
LGTM, thank you @randomicon00, nice work!

2022-05-14 10:00 UTC, merged