refactor(ext/url): URLPattern structured matchers
denoland/deno pull request #14502
Opened 2022-05-05 18:26 UTC by lucacasonato

This commit updates URLPattern to use a structured matcher instead of
always using a RegExp. This results in an approximately 0% change in performance
 in the cases I tested. The real value of this PR is that it allows for
 very fast matching in the upcoming URLPatternList, because this
interface can be implemented to use a radix tree matcher internally.

The new matcher still falls back to RegExp matching if the pattern is
too complicated to be handled by the simple cases (for example if
backtracking is required to match).

2022-05-06 13:32 UTC, crowlKats commented on ext/url/Cargo.toml
> +urlpattern = { git = "https://github.com/lucacasonato/rust-urlpattern", branch = "fast_matcher" }
update this

2022-05-06 13:33 UTC, crowlKats approved these changes
LGTM besides the git import

2022-05-09 17:52 UTC, bartlomieju requested changes

2022-05-09 17:52 UTC, bartlomieju commented on cli/flags.rs
> -  runtime_args(Command::new("bench"), true, false)
Unrelated change?

2022-05-09 17:52 UTC, bartlomieju commented on cli/tools/bench.rs
> +      worker.run_event_loop(true).await?;
Ditto

2022-05-09 17:53 UTC, bartlomieju commented on cli/tools/bench.rs
> +      worker.run_event_loop(true).await?;
Good catch, but let's do that in a separate PR. I thought I did exclude `--inspect` flags from `deno bench`

2022-05-09 17:54 UTC, bartlomieju approved these changes
LGTM, if you revert changes to `cli/flags.rs` and `cli/tools/bench.rs`

2022-07-21 05:37 UTC, closed without merging