remove deprecated Deno APIs
denoland/deno pull request #14733
Opened 2022-05-26 13:48 UTC by bartlomieju

Ref https://github.com/denoland/deno/issues/9795

2022-05-26 14:08 UTC, dsherret commented on cli/dts/lib.deno.ns.d.ts
> -   * instead. `Deno.copy` will be removed in Deno 2.0.
"Will be removed in Deno 2.0"

2022-05-26 14:10 UTC, dsherret reviewed
The comments in the file say that this functionality will be removed in Deno 2.0 so I think we should close this PR and wait for Deno 2.0 unless this PR is for Deno 2.0. The other changes we've been doing are for unstable APIs, but these are stable APIs.

2022-05-26 14:12 UTC, lucacasonato requested changes
I agree with David. Not at all semver compatible. There is still a lot of code out there that uses these APIs. There is no rush to remove them.

2022-05-27 13:33 UTC, dsherret commented on cli/dts/lib.deno.ns.d.ts
> +   * `writeAll()` from https://deno.land/std/streams/conversion.ts instead.
We should merge this in a separate PR.

2022-05-28 01:21 UTC, ry commented
we'll wait...

2022-05-28 01:21 UTC, closed without merging