perf(ext/ffi): optimize synchronous calls
denoland/deno pull request #14945
Opened 2022-06-23 04:16 UTC by littledivy

This commit implements an optimization
for blocking FFI calls. 

`op_ffi_load` creates JS functions for 
synchronous symbols. This avoids 
reallocations that existed in `op_ffi_call`
and allows future V8 fast API optimizations.

Each function owns an allocation to corresponding
the Symbol, which is freed on GC.

Nonblocking ops & statics are still registered JS
side and use ops to make calls.

![image](https://user-images.githubusercontent.com/34997667/175207754-46acbf56-a3ff-406c-928c-bae3f8b329f7.png)

2022-06-23 06:33 UTC, bartlomieju approved these changes
LGTM, these are very impressive results

2022-06-23 08:25 UTC, lucacasonato commented
I want to discuss this in CLI design meeting, because it bypasses ops.

2022-06-23 08:25 UTC, lucacasonato commented
Also unintentional SWC downgrade?

2022-06-23 09:20 UTC, aapoalas commented on ext/ffi/lib.rs
> +      let result = ffi_call_sync(scope, args, symbol).unwrap();
Should handle errors.

2022-06-23 10:37 UTC, bartlomieju commented
> Also unintentional SWC downgrade?

How so?

2022-06-23 10:37 UTC, bartlomieju commented on ext/ffi/lib.rs
> +      let result = ffi_call_sync(scope, args, symbol).unwrap();
Good point, I've missed that

2022-06-23 10:37 UTC, bartlomieju requested changes
https://github.com/denoland/deno/pull/14945#discussion_r904866038

2022-06-23 10:38 UTC, lucacasonato commented
> How so?

Look at cli/Cargo.toml

2022-06-23 10:43 UTC, bartlomieju commented
> > How so?
> 
> Look at cli/Cargo.toml

<img width="340" alt="Screenshot 2022-06-23 at 12 42 49" src="https://user-images.githubusercontent.com/13602871/175281063-c3b0ffdc-8c84-4fe8-a581-fde012bbfd04.png">

I see only two changed files

2022-06-23 10:54 UTC, lucacasonato commented
Huh, on the GitHub mobile app I see a bunch more changed files. I guess must be a bug. It looks correct on the website... sorry for the noise.

2022-06-28 17:19 UTC, bartlomieju approved these changes

2022-06-29 08:13 UTC, merged