fix(task): remove --no-config as task subcommand argument
denoland/deno pull request #14983
Opened 2022-06-27 18:38 UTC by GJZwiers

Fixes #14971.

2022-06-27 19:27 UTC, bartlomieju requested changes

2022-06-27 19:27 UTC, bartlomieju commented on cli/flags.rs
> +    .value_hint(ValueHint::FilePath)
Consider splitting `config_args()` into `config_arg` and `no_config_arg` and applying them to all relevant subcommands. I think this is better than duplicating arg definition

2022-06-28 17:52 UTC, bartlomieju reviewed
One nit, but besides LGTM

2022-06-28 18:00 UTC, GJZwiers commented on cli/args/flags.rs
> +fn task_args_parse(flags: &mut Flags, matches: &ArgMatches) {
Will do!

2022-06-28 19:47 UTC, merged