fix: Cache passed type checks for many configs
denoland/deno pull request #15090
Opened 2022-07-05 18:59 UTC by nayeemrmn

Discussed on Discord a couple times.
```ts
// temp.ts
console.log("Hello, world!");

// temp.json
{
  "compilerOptions": {
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ]
  }
}
```
Before:
```
$ deno check temp.ts
Check file:///home/nayeem/projects/deno/temp.ts
$ deno check -c temp.json temp.ts
Check file:///home/nayeem/projects/deno/temp.ts
$ deno check temp.ts
Check file:///home/nayeem/projects/deno/temp.ts
$ deno check -c temp.json temp.ts
Check file:///home/nayeem/projects/deno/temp.ts
```
After:
```
$ deno check temp.ts
Check file:///home/nayeem/projects/deno/temp.ts
$ deno check -c temp.json temp.ts
Check file:///home/nayeem/projects/deno/temp.ts
$ deno check temp.ts
$ deno check -c temp.json temp.ts
```

2022-07-05 23:11 UTC, kitsonk commented
I will defer to @dsherret as he has been investigating cache validation challenges as a whole.

2022-07-06 19:39 UTC, dsherret requested changes
I think this breaks a few things, but overall I'm not sure this is worth the complexity especially now that --no-check is the default.

2022-07-06 19:39 UTC, dsherret commented on cli/cache.rs
> +  pub type_checks_succeeded: HashSet<String>,
This name feels like a boolean. Any other ideas? Perhaps `type_check_hashes` with a comment saying it only contains successful hashes?

2022-07-06 19:39 UTC, dsherret commented on cli/cache.rs
> +  pub type_checks_succeeded: HashSet<String>,
Does this handle this property not existing when deserializing?

2022-07-06 19:39 UTC, dsherret commented on cli/emit.rs
> +  let mut input = vec![ts_config.as_bytes(), vec![mode as u8]];
This vector could be preallocated to prevent resizing: `let mut input = Vec::with_capacity(2 + roots.len() * 2);`

2022-07-06 21:36 UTC, dsherret commented on cli/emit.rs
> -            version_hash: get_version(source_bytes, &config_bytes),
It makes caching a lot more complicated and I'm still not sure it's worth it. It seems much easier and less error prone to just invalidate all the caches whenever the config changes. How often do people have multiple configs or no config and then a config when type checking? Is this actually something users need?

2022-07-06 21:36 UTC, nayeemrmn commented on cli/emit.rs
> -            version_hash: get_version(source_bytes, &config_bytes),
It happens with workers also

2022-07-07 00:07 UTC, nayeemrmn commented
@dsherret I remembered why I wanted to do this, last time it came up was discussing #14632. We could fix shortly fix that just by including the check scope in the config digest. But looking at the cache validation code I strongly think we need better separation between things that bust the emit cache, when a type check needs to be reperformed and tracking if the source has actually changed. As described in https://github.com/denoland/deno/pull/15090#discussion_r915235504. One of the reasons is that invalid emits from changed sources need to be checked for each module in the graph uniformly, whereas checked state can only correctly be stored at the roots. Another is that some files aren't emitted at all but changes need to be tracked only for type checking.

There have always been odd cache validation bugs and I attribute it to the current structure which conflates invalid emits and yet-to-be-performed type checks and tries to store it all in one version hash. But again I can make a better case and implementation for this _after_ checking and emitting are properly decoupled with swc. Closing for now.

2022-07-07 00:07 UTC, closed without merging

2022-07-07 00:24 UTC, dsherret commented
@nayeemrmn yeah, I think decoupling the two would be really good. I was planning on starting work tomorrow on #13302. Maybe at the same time I will look a bit at decoupling it.

2022-07-07 18:27 UTC, dsherret commented
I looked into this today and the type checking cache seems like it won't be invalidated in more scenarios than mentioned in the original issue. I'm updating the code to cache a hash of all the inputs per successful type check which is only cleared when changing CLI versions, so it will solve this issue too.