fix(ext/crypto): fix importKey error when leading zeroes
denoland/deno pull request #16009
Opened 2022-09-23 15:25 UTC by liruifengv

fix https://github.com/denoland/deno/issues/15126

2022-09-23 15:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno?pullRequest=16009) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno?pullRequest=16009) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno?pullRequest=16009) it.</sub>

2022-09-23 16:26 UTC, cjihrig reviewed
The CI is failing in the linting job. Can you run `./tools/format.js` and `./tools/lint.js` locally and commit the changes.

2022-09-23 16:26 UTC, cjihrig commented on ext/crypto/import_key.rs
> +  val = new_val.as_slice();
You can avoid making `val` mutable:

```suggestion
  let val = new_val.as_slice();
```

2022-09-24 04:51 UTC, liruifengv commented on ext/crypto/import_key.rs
> +  val = new_val.as_slice();
Thanks. I fixed it.

2022-09-24 11:27 UTC, CGQAQ requested changes

2022-09-24 11:27 UTC, CGQAQ commented on ext/crypto/import_key.rs
> +  }
```suggestion
  new_bytes.extend_from_slice(&original_bytes);
```

2022-09-24 11:27 UTC, CGQAQ commented on ext/crypto/import_key.rs
> +  let mut new_val: Vec<u8> = vec![0; 32 - val.len()];
```suggestion
  let original_bytes = val.as_bytes();
  let mut new_bytes: Vec<u8> = vec![0; 32 - original_bytes.len()];
```

2022-09-24 11:27 UTC, CGQAQ commented on ext/crypto/import_key.rs
> +  let val = new_val.as_slice();
```suggestion
  let val = new_bytes.as_slice();
```

2022-09-30 15:17 UTC, cjihrig approved these changes
LGTM. Thoughts @littledivy?

2022-10-03 04:07 UTC, littledivy approved these changes
LGTM

2022-10-03 04:07 UTC, merged