fix(ext/web): use mimesniff in FileAPI
denoland/deno pull request #16233
Opened 2022-10-10 11:33 UTC by marcosc90

ref: #16225

2022-10-10 17:59 UTC, marcosc90 commented
Managed to get to `1896/1898` up from 1027, but it now conflicts with `FileAPI` tests.

https://github.com/web-platform-tests/wpt/issues/36377

2022-10-11 08:27 UTC, marcosc90 commented
FileAPI spec is broken:

https://github.com/w3c/FileAPI/issues/43
https://github.com/w3c/FileAPI/issues/122

I think we should favor MIME Sniffing spec, and disable the broken FileAPI tests.

2022-10-31 10:05 UTC, marcosc90 commented on tools/wpt/expectation.json
> +          "Default Content-Type for Request with Blob body (set type)",
This fails because it expects `a/b; c=d`, but we're now setting to `a/b;c=d` as per the MIME Sniffing spec

2023-01-01 21:51 UTC, jimmywarting commented
👍 finally time someone did something about this.
have long been waiting for meta values to not be casted into lowercase, as that only breaks the real value (https://github.com/whatwg/html/issues/6251)

The WPT test should be changed to match the mime sniffing api IMO

2023-03-25 11:31 UTC, aapoalas requested changes
Hello, could you rebase this please? It seems like the spec issues have at least moved forward a little?

2025-03-21 02:31 UTC, ry commented
closing this because it's old

2025-03-21 02:31 UTC, closed without merging