fix(cli/http_cache): metadata: handle errors, make headers optional
denoland/deno pull request #16300
Opened 2022-10-15 19:49 UTC by milahu

fix #16295

early draft

work in progress

2022-10-15 19:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno?pullRequest=16300) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno?pullRequest=16300) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno?pullRequest=16300) it.</sub>

2022-10-15 23:14 UTC, milahu commented
before

<pre>
<span color=red>error</span>: missing field `headers` at line 3 column 1
    at file:///run/user/1017/tmp.RAmiZXZKll/deps.ts:1:36
</pre>

after

<pre>
<span color=red>error</span>: Unable to parse metadata for https://deno.land/std@0.150.0/flags/mod.ts
    at file:///run/user/1017/tmp.OPoLI03mtc/deps.ts:1:36
</pre>

im not happy with the error message ...

ideally i want

<pre>
<span color=red>error</span>: missing field `url`
    at file:///run/user/1017/tmp.IF20N3hyLc/deps/https/deno.land/851d4afb1650b725c8358e5b5dcd71c16f5741d4df406497977206eeccaa745d.metadata.json:1:2
    at https://deno.land/std@0.150.0/flags/mod.ts
    at file:///run/user/1017/tmp.OPoLI03mtc/deps.ts:1:36
</pre>

<details>
<summary>
or
</summary>

<pre>
<span color=red>error</span>: missing field `url` in metadata for https://deno.land/std@0.150.0/flags/mod.ts
    at file:///run/user/1017/tmp.IF20N3hyLc/deps/https/deno.land/851d4afb1650b725c8358e5b5dcd71c16f5741d4df406497977206eeccaa745d.metadata.json:1:2
    at file:///run/user/1017/tmp.OPoLI03mtc/deps.ts:1:36
</pre>

or

<pre>
<span color=red>error</span>: missing field `url` in file:///run/user/1017/tmp.IF20N3hyLc/deps/https/deno.land/851d4afb1650b725c8358e5b5dcd71c16f5741d4df406497977206eeccaa745d.metadata.json:1:2
    at https://deno.land/std@0.150.0/flags/mod.ts
    at file:///run/user/1017/tmp.OPoLI03mtc/deps.ts:1:36
</pre>

</details>

with this `*.metadata.json` file

```json
{}
```

how can i add lines to the stack trace?

@bartlomieju ideas?

2023-03-25 11:22 UTC, aapoalas requested changes
Is this still relevant?

2024-07-10 03:21 UTC, dsherret commented
Thanks, but going to close this one because the http cache moved over here: https://github.com/denoland/deno_cache_dir/blob/1558da51fede98f28be58078e6a435d8a0559058/rs_lib/src/cache.rs#L105

2024-07-10 03:21 UTC, closed without merging