feat(ext/weblocks): tests
denoland/deno pull request #16566
Opened 2022-11-08 04:08 UTC by load1n9

2022-11-18 16:08 UTC, sgwilym commented
Seems like this is failing on a formatting issue?

2022-11-30 13:19 UTC, crowlKats requested changes

2022-11-30 13:19 UTC, crowlKats commented on ext/weblocks/00_weblocks.js
> +    mode;
these should be using symbols and getters for the ones that need them

2022-11-30 13:19 UTC, crowlKats commented on ext/weblocks/00_weblocks.js
> +    constructor(name, mode = LockMode[0], buffer = null) {
should be a illegal constructor and use `webidl.createBranded` and assign that way.

2022-11-30 13:19 UTC, crowlKats commented on ext/weblocks/00_weblocks.js
> +    enter(handler) {
should use symbol. needs webidl brand check.

2022-11-30 13:19 UTC, crowlKats commented on ext/weblocks/00_weblocks.js
> +    tryEnter() {
should use symbol. needs webidl brand check.

2022-11-30 13:19 UTC, crowlKats commented on ext/weblocks/00_weblocks.js
> +    leave() {
should use symbol. needs webidl brand check.

2022-11-30 13:19 UTC, crowlKats commented on ext/weblocks/00_weblocks.js
> +  class LockManagerSnapshot {
not a class, but a plain object.

2022-11-30 13:19 UTC, crowlKats commented on ext/weblocks/00_weblocks.js
> +    [webidl.brand] = webidl.brand;
brand not necessary because of createBranded call.

2022-11-30 13:19 UTC, crowlKats commented on ext/weblocks/00_weblocks.js
> +    }
I dont see these in the spec.

2022-12-19 13:44 UTC, load1n9 commented
sadly I have come to believe that adding web locks now would be a terrible idea.  Writing a full weblocks implementation would require a whole system to store data across instances which eventually should be added to deno but adding it just for weblocks seems unnecessary so I believe it would be better to implement some more multithreading features before rewriting the weblocks api

2023-01-10 19:17 UTC, closed without merging