feat(ext/http): websockets over h2
denoland/deno pull request #16687
Opened 2022-11-17 20:06 UTC by AaronO

A first pass at supporting WebSockets over http/2 server-side.

A few notes & minor pending items:
- Unclear how we should expose pseudo-headers like `:protocol` to userspace, I don't think there's precedent, since other pseudo-headers like `:method`, `:path`, `:authority` are mostly handled as one-offs and map to h1 semantics
- We don't support ws-over-h2 client-side, making it a little more tedious to test

2023-02-12 19:48 UTC, aapoalas commented
Sorry, can you rebase this? Thank you <3

2023-03-19 13:40 UTC, aapoalas commented on ext/http/01_http.js
> +    // TODO(somebody): validate :protocol, pseudo-header
Mark this Todo to me, I guess.

2023-03-25 10:58 UTC, aapoalas requested changes
Requires a rebase at least. I'd be in favour of merging this as it is and simply making a note of adding tests when WebSocket over HTTP/2 client support is implemented.

2025-03-21 02:32 UTC, ry commented
closing this because it's old

2025-03-21 02:32 UTC, closed without merging