fix(permissions): accept URL in `Deno.FfiPermissionDescriptor.path` for `revoke()` and `request()`
denoland/deno pull request #17094
Opened 2022-12-17 06:23 UTC by iuioiua

Previously, `Deno.permissions.[revoke|request]()`couldn't accept a URL in the `path` argument when `name` was `ffi`. This change fixes that behaviour and adds a new function, `formDescriptor()`, to ensure `URL` arguments are consistently handled across `Deno.permissions.[query|revoke|request]()`.

Fixes #17020.

2022-12-17 08:06 UTC, iuioiua commented
Where is the best place to write a regression test?

2022-12-19 13:40 UTC, bartlomieju commented
> Is a regression test for this change needed?

Yes, it would be good to have a test for it @iuioiua

2022-12-20 05:38 UTC, iuioiua commented
Note: this is needed for #17019.

2022-12-22 11:10 UTC, petamoriken commented
@iuioiua It seems that the last commit rolled back the deno_third_party submodule.

2022-12-22 22:10 UTC, iuioiua commented
Was it updated or rolled back? How do I fix it? I'm not familiar with submodules.

2022-12-22 22:49 UTC, bartlomieju commented
> Was it updated or rolled back? How do I fix it? I'm not familiar with submodules.

Pull latest `main`, merge it into this branch, run `git submodule update --init --recursive`, `git add third_party/`, `git commit`.

2022-12-26 10:00 UTC, iuioiua commented
Fixed

2022-12-26 11:47 UTC, petamoriken requested changes

2022-12-26 11:47 UTC, petamoriken commented on ext/fetch/20_headers.js
> -      // deno-lint-ignore prefer-primordials
Please restore this line.

2022-12-26 11:47 UTC, petamoriken commented on ext/fetch/21_formdata.js
> -    // deno-lint-ignore prefer-primordials
same here

2022-12-26 11:47 UTC, petamoriken commented on ext/web/09_file.js
> -      // deno-lint-ignore prefer-primordials
sane here

2022-12-26 23:15 UTC, iuioiua commented on ext/fetch/20_headers.js
> -      // deno-lint-ignore prefer-primordials
Thanks. Idk why I did that

2022-12-26 23:15 UTC, iuioiua commented on ext/fetch/20_headers.js
> -      // deno-lint-ignore prefer-primordials
Thanks. Idk why I did that

2022-12-31 07:09 UTC, lino-levan commented
LGTM

2023-01-03 20:50 UTC, bartlomieju approved these changes
LGTM, thanks for fixing this @iuioiua!

2023-01-03 20:50 UTC, merged