fix(lsp): sort quickfix actions
denoland/deno pull request #17221
Opened 2022-12-29 21:49 UTC by bartlomieju

This commit changes ordering of quickfix actions, by sorting them in following order:

- TSC fixes
- Deno fixes
- deno_lint fixes

Closes https://github.com/denoland/deno/issues/15069

Still need to add a test and debate if TSC should have priority over Deno fixes.

2022-12-29 22:02 UTC, bartlomieju commented
I'm thinking that diagnostics coming from "deno" scope should come before diagnostics from "tsc", these include diagnostics related to import maps, uncached specifiers or non-existent local files.

2023-05-18 10:06 UTC, aapoalas approved these changes
Looks good to me.

2023-07-07 19:18 UTC, aapoalas requested changes
Some tests fail, which is good! The tests are working.

2023-09-03 20:07 UTC, bartlomieju commented
@nayeemrmn could you finish this PR and shepherd it to landing?

2023-09-04 05:49 UTC, nayeemrmn commented
> I'm thinking that diagnostics coming from "deno" scope should come before diagnostics from "tsc", these include diagnostics related to import maps, uncached specifiers or non-existent local files.

I think tsc first is better. That contains more urgent fixes, and the only reason Deno doesn't implement them is because tsc does.

@aapoalas Please do a quick look through of test changes.

2023-09-06 19:25 UTC, nayeemrmn approved these changes
LGTM (from co-author)

2023-09-17 18:05 UTC, merged

2023-09-17 21:47 UTC, dsherret commented on cli/lsp/analysis.rs
> +        a.title.cmp(&b.title)
Is this correct? Perhaps we should maintain TypeScript's diagnostic sort order instead of sorting alphabetically?

2023-09-17 21:55 UTC, dsherret commented on cli/lsp/analysis.rs
> +        a.title.cmp(&b.title)
I opened https://github.com/denoland/deno/issues/20544 -- we should restore the sorting order to align with typescript.