feat: sendBeacon
denoland/deno pull request #17337
Opened 2023-01-10 21:05 UTC by load1n9

sendBeacon api implementation 
spec: https://w3c.github.io/beacon/#sendbeacon-method

2023-01-10 21:08 UTC, crowlKats commented on ext/fetch/26_fetch.js
> +    const prefix = "Failed to construct 'Beacon'";
```suggestion
    const prefix = "Failed to execute 'sendBeacon'";
```

2023-01-12 12:54 UTC, crowlKats commented
sadly due to the fact that the wpts use iframes, tests will have to be written manually

2023-02-12 19:25 UTC, aapoalas commented
One WPT test failing, also needs rebase now.

2023-02-12 19:27 UTC, crowlKats commented
yea, i have to look into the wpt, will try to make it for the release

2023-04-29 17:24 UTC, lino-levan commented
@load1n9 could you rebase?

2023-07-11 19:37 UTC, aapoalas requested changes
**issue:** I realized that the spec requires `sendBeacon` to return a synchronous boolean value, and not a Promise that resolves with a boolean like here.

Properly implementing this API will require binding into the Rust side of the HTTP implementation.

2023-07-11 19:43 UTC, lino-levan commented
My understanding of the spec is that it DOES returns a synchronous boolean value, but it sends the actual data asynchronously. It returns `true` after the data has been queued (after fetch is constructed in this case?). I don't think we need rust bindings for this functionality.

2023-07-11 23:32 UTC, lino-levan requested changes
Two big things:
- `sendBeacon` returns a promise when it should not be doing so
- `sendBeacon` should set `keepAlive` which it doesn't seem to be doing

2023-09-07 12:23 UTC, closed without merging