fix(ext): log class for class constructor
denoland/deno pull request #17615
Opened 2023-02-01 16:01 UTC by MarybethGasman

fix #17197
add check for class constructor

2023-02-01 16:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno?pullRequest=17615) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno?pullRequest=17615) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno?pullRequest=17615) it.</sub>

2023-02-01 23:55 UTC, bartlomieju commented
Nice fix @MarybethGasman! There are some tests that are failing due to this change (rightly so!), could you please update the output of relevant tests to make CI happy?

2023-02-02 00:43 UTC, MarybethGasman commented
I think our CI is happy again!
cheers!
BTW, @tannal is me too. (seems like I have a broken git config.😀)

2023-02-03 13:15 UTC, petamoriken requested changes

2023-02-03 13:15 UTC, petamoriken commented on ext/console/02_console.js
> +    if (stringValue.startsWith("class")) {
same here

```suggestion
    if (StringPrototypeStartsWith(stringValue, "class")) {
```

2023-02-03 13:15 UTC, petamoriken commented on ext/console/02_console.js
> +    }
Please use primordials

```suggestion
    const stringValue = FunctionPrototypeToString(value);
```

2023-02-03 13:52 UTC, MarybethGasman commented on ext/console/02_console.js
> +    }
Sounds good
Thanks for reminding me

2023-02-04 23:34 UTC, bartlomieju approved these changes
LGTM, great fix @MarybethGasman, thank you!

2023-02-04 23:34 UTC, merged