Fix Typos
denoland/deno pull request #17665
Opened 2023-02-06 11:49 UTC by ACGNnsj

🙂I've fixed typos in some files.

2023-02-06 11:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno?pullRequest=17665) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno?pullRequest=17665) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno?pullRequest=17665) it.</sub>

2023-02-06 15:36 UTC, dsherret commented on cli/tsc/README.md
> +8. Review the copied files, removing and reverting what's necessary
It being all `1`s is a way to have an automatically numbered list https://stackoverflow.com/a/12145270/188246

2023-02-07 20:21 UTC, dsherret approved these changes
LGTM. Thanks!

2023-02-07 20:26 UTC, dsherret requested changes
It seems there's some conflicts now. I fixed them, but then I can't push to your repo because the PR was done from your main branch:

```
To https://github.com/ACGNnsj/deno.git
 ! [remote rejected]     ACGNnsj/main -> ACGNnsj/main (permission denied)
error: failed to push some refs to 'https://github.com/ACGNnsj/deno.git'
```

2023-02-09 03:35 UTC, ACGNnsj commented
> confli

Thanks for the reminder, and I've solved the conflicts. 🙂

2023-02-10 01:43 UTC, dsherret commented
It's failing the lint step. Can you run `deno run -A ./tools/format.js`?

2023-02-10 01:44 UTC, dsherret requested changes
It's failing the lint step. Can you run `deno run -A ./tools/format.js`?

2023-03-14 20:29 UTC, aapoalas requested changes
@ACGNnsj Unfortunately there're new conflicts to handle, and format presumably still needs to be run. I'd like to get this merged :)

2023-03-15 09:53 UTC, closed without merging