compat(node/http): polyfill `ClientRequest.setTimeout()`
denoland/deno pull request #17961
Opened 2023-02-26 18:11 UTC by schwarzkopfb

Add a simple implementation of `ClientRequest.setTimeout()` that simulates Node's behaviour. Fixes #17852 and eliminates the excess warning messages ("not implemented...") from stdout that appeared in #16810.

2023-02-26 18:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno?pullRequest=17961) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno?pullRequest=17961) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno?pullRequest=17961) it.</sub>

2023-03-13 13:11 UTC, bartlomieju reviewed
Looks good! Thanks for the PR @schwarzkopfb. It would be great to enable some of the Node.js tests to ensure that this functionality works as expected. @kt3k could you advise here?

2023-03-13 13:11 UTC, bartlomieju commented on ext/node/polyfills/http.ts
> +    if (this.#timeout) clearTimeout(this.#timeout);
This looks okay - but I suggest you use `AbortController` and pass `signal` option to `fetch` call created in `_final` - that way you will be able to properly cleanup all resources and ensure there are no funky race conditions going on (it is my understanding that after firing `timeout` event response might still fire another event.

2023-03-14 19:29 UTC, aapoalas requested changes
As @bartlomieju said, we'll need to find a test to enable to go along with this, and using `AbortController` sounds like a good idea.

2023-04-23 21:11 UTC, levex commented
I think we can close this given that #18783 was merged, @bartlomieju @schwarzkopfb ?

2023-04-23 21:16 UTC, bartlomieju commented
Yeah! Thanks for the PR @schwarzkopfb, but gonna close without merge.

2023-04-23 21:16 UTC, closed without merging