feat(fmt): add ability to prefer single lines
denoland/deno pull request #18681
Opened 2023-04-12 23:24 UTC by yardenshoham

Adds the option to format things in a nicer way (in my opinion)

For example, this block of code remains the same after running the default `deno fmt`:
```ts
console.log(
  "deno version",
  Deno.version,
);
```

If we run `deno fmt --prefer-single-line`:
```ts
console.log("deno version", Deno.version);
```

2023-04-12 23:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno?pullRequest=18681) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno?pullRequest=18681) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno?pullRequest=18681) it.</sub>

2023-04-13 13:42 UTC, dsherret requested changes
We can't add this at this time because the "prefer-single-line" config in dprint is not stable. I'd probably need to spend a month on it. Also, this shouldn't be a configuration setting, but just something that happens. Sorry, but going to decline this one.

2023-04-13 13:43 UTC, yardenshoham commented
So when it becomes stable it'll become true by default?

2023-04-13 13:46 UTC, dsherret commented
Yes, for certain scenarios like this one.

2023-04-13 13:46 UTC, yardenshoham commented
Ok, thank you.

2023-04-13 13:46 UTC, closed without merging

2023-04-14 09:36 UTC, yardenshoham commented
@dsherret is there a possibility to add this as an unstable/experimental feature in the meanwhile? Just an opt-in option so I'll be able to use it?

2023-04-15 16:54 UTC, lucacasonato commented
No. Use dprint.dev if you'd like to use experimental features.