fix(core): let V8 drive extension ESM loads
denoland/deno pull request #18997
Opened 2023-05-05 12:36 UTC by lucacasonato

This now allows circular imports across extensions.

Instead of load + eval of all ESM files in declaration order, all files
are only loaded. Eval is done recursively by V8, only starting at
`esm_entry_point`s.

2023-05-06 19:04 UTC, aapoalas requested changes
@bartlomieju 's change to fix one test apparently broke a hundred and six others?

2023-05-06 22:03 UTC, bartlomieju commented
> @bartlomieju 's change to fix one test apparently broke a hundred and six others?

Not really, fixing that test just surfaced all these errors. It's a bug in the logic of this PR. I will fix it and merge at first convenience.

2023-05-08 20:56 UTC, bartlomieju commented on ext/crypto/01_webidl.js
> -// Copyright 2018-2023 the Deno authors. All rights reserved. MIT license.
There was a circular dependency on `CryptoKey` between this file and `00_crypto.js` (which uses relevant WebIDL converters). I moved this file into `00_crypto.js`.

2023-05-08 20:56 UTC, bartlomieju commented on ext/web/09_file.js
> +function createObjectURL(blob) {
Moved these two functions from `11_blob_url.js` which is not explicitly imported by any file.

2023-05-08 21:29 UTC, bartlomieju approved these changes
LGTM

2023-05-09 10:37 UTC, lucacasonato reviewed
LGTM

2023-05-09 10:37 UTC, merged