fix(watch): restore env between runs
denoland/deno pull request #19024
Opened 2023-05-07 10:01 UTC by denizdogan

Fixes #15883

Let me know what you think?

----

I wasn't able to run the linter because of some unrelated issues, not sure what that's about:

```
error: the borrowed expression implements the required traits
   --> ext/fs/std_fs.rs:437:44
    |
437 |         let mut from_file = fs::File::open(&from)?;
    |                                            ^^^^^ help: change this to: `from`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
    = note: `-D clippy::needless-borrow` implied by `-D clippy::all`

error: the borrowed expression implements the required traits
   --> ext/fs/std_fs.rs:446:17
    |
446 |           .open(&to)?;
    |                 ^^^ help: change this to: `to`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

error: could not compile `deno_fs` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `deno_fs` due to 2 previous errors
error: could not compile `deno_fs` due to 2 previous errors
error: Uncaught (in promise) Error: clippy failed
    throw new Error("clippy failed");
          ^
    at clippy (file:///Users/deniz/Code/denoland/deno/tools/lint.js:165:11)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async file:///Users/deniz/Code/denoland/deno/tools/lint.js:21:3
```

2023-05-07 10:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno?pullRequest=19024) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno?pullRequest=19024) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno?pullRequest=19024) it.</sub>

2023-05-07 20:05 UTC, bartlomieju reviewed
Looks good! Could you add a test to `cli/tests/integration/watcher_tests.rs` that checks this functionality end-to-end?

2023-05-07 20:05 UTC, bartlomieju commented
> I wasn't able to run the linter because of some unrelated issues, not sure what that's about:

Thanks for pointing this out, I will fix it in a separate PR.

2023-05-08 22:58 UTC, bartlomieju requested changes
I'm marking this a "Request changes" as this PR requires further discussion. It appears that adding this functionality enabled by default will break things like Fresh. Where `dev.ts` script relies on environment variable being persisted.

That said, this PR is small and I can see where it can be useful. Maybe as a middle ground we can enable with with a flag like `--reset-env`.

2023-05-09 08:46 UTC, denizdogan commented
@bartlomieju I will nevertheless add the watcher tests soon, just so they're there.

While I was working on this, I was wondering if maybe this would make more sense as a sort of `--watch --child-process` option, where instead of restarting the main worker, Deno could be managing a separate child process, and then restart the child process when it detects changes?

That child process would then basically be executed using the same command line, except for `--watch`, `--childprocess`, and potentially a number of other flags.

That way, we could cover more than just resetting the environment, but also other potential resources, not sure what, maybe file handles and such?

2025-03-21 02:35 UTC, ry commented
closing this because it's old

2025-03-21 02:35 UTC, closed without merging