fix: Allow for logging URL/URLPattern.prototype
denoland/deno pull request #19144
Opened 2023-05-16 11:43 UTC by kamilogorek

Instead of throwing, it now prints:

```
Object [URL] {
  hash: [Getter/Setter],
  host: [Getter/Setter],
  hostname: [Getter/Setter],
  href: [Getter/Setter],
  origin: [Getter],
  password: [Getter/Setter],
  pathname: [Getter/Setter],
  port: [Getter/Setter],
  protocol: [Getter/Setter],
  search: [Getter/Setter],
  username: [Getter/Setter],
  searchParams: [Getter],
  toString: [Function: toString],
  toJSON: [Function: toJSON]
}
```

Alternatively, we can use `createFilteredInspectProxy` which will skip `toString/toJSON`, but keys wont be sorted, eg.:

```js
[SymbolFor("Deno.privateCustomInspect")](inspect, inspectOptions) {
  return `${this.constructor.name} ${inspect(createFilteredInspectProxy({
    object: this,
    evaluate: ObjectPrototypeIsPrototypeOf(URL.prototype, this),
    keys: [
      "href",
      "origin",
      "protocol",
      "username",
      "password",
      "host",
      "hostname",
      "port",
      "pathname",
      "hash",
      "search",
    ],
  }), inspectOptions)}`;
}

```
URL URL {
  href: [Getter/Setter],
  origin: [Getter],
  protocol: [Getter/Setter],
  username: [Getter/Setter],
  password: [Getter/Setter],
  host: [Getter/Setter],
  hostname: [Getter/Setter],
  port: [Getter/Setter],
  pathname: [Getter/Setter],
  hash: [Getter/Setter],
  search: [Getter/Setter
}
```

2023-05-16 11:46 UTC, crowlKats commented
could we get a test?

2023-05-16 12:01 UTC, kamilogorek commented
It looks like there was already a test that tested a part of it, which broke now. Will get back to it later and fix it up.

2023-05-16 13:24 UTC, kamilogorek commented on cli/tests/testdata/run/prototype_logging.ts
> +console.log(URLPattern.prototype);
No specific reason, I just found `070_location.ts` test which does something very similar, and decided to put it in the same place.

2023-05-17 15:55 UTC, bartlomieju requested changes
Marking as "Request changes" because we discovered that the same problem appears for other Web APIs. @crowlKats will look into more general solution next week.

2024-04-12 15:11 UTC, closed without merging