fix(ext/http): fix a possible memleak in Brotli
denoland/deno pull request #19250
Opened 2023-05-25 10:37 UTC by levex

We probably need to free the BrotliEncoderState once the stream has finished.

2023-05-25 13:16 UTC, mmastrac requested changes
Let's add impl Drop instead -- there are potentially cases where the response may be dropped and never complete as expected.

2023-05-25 13:19 UTC, ry reviewed
Is it possible to add a test for this? Unit test or otherwise?

2023-05-25 13:33 UTC, levex commented
Don't think it's possible - I'm not even sure at the moment if it's a valid memory leak. I literally had a dream about this. Do we have a benchy for memory usage that could potentially show the impact of my previous change? I submitted this to the CI to verify that there are no double frees.

impl Drop would solve this, but I'm not sure how that interfaces with the FFI.

2023-05-25 16:13 UTC, littledivy commented
+1 for a Drop impl to prevent use-after-free

2023-05-26 13:47 UTC, levex commented
`impl Drop` ✅

2023-05-28 01:38 UTC, mmastrac approved these changes
LGTM with Drop!

2023-05-28 04:10 UTC, littledivy approved these changes
LGTM

2023-05-28 15:53 UTC, levex commented
@bartlomieju can you merge this please?

2023-05-28 18:30 UTC, merged