perf(ext/websocket): Cut event dispatch/blob overhead as much as we can
denoland/deno pull request #19386
Opened 2023-06-06 14:34 UTC by mmastrac

Small improvement, seems to reduce benchmark jitter a bit. I was not able to see any major differences with `--trace-gc`, but the results are consistently better (average is higher and std dev is much lower)

Before:

```
Msg/sec: 155174.750000
Msg/sec: 160164.250000
Msg/sec: 164021.750000
Msg/sec: 164089.750000
Msg/sec: 161876.000000
Msg/sec: 164591.750000
Msg/sec: 166381.000000
Msg/sec: 165368.500000
Msg/sec: 152099.000000
Msg/sec: 160498.000000
```

After:

```
Msg/sec: 165066.250000
Msg/sec: 163997.750000
Msg/sec: 166492.500000
Msg/sec: 167396.500000
Msg/sec: 167681.500000
Msg/sec: 164960.500000
Msg/sec: 165815.000000
Msg/sec: 166636.250000
Msg/sec: 166958.000000
Msg/sec: 166451.250000
Msg/sec: 166227.750000
Msg/sec: 165989.750000
```

2023-06-06 15:01 UTC, bartlomieju commented on ext/websocket/01_websocket.js
> +          dispatchFast(this, event);
There are other places in this file where we could use this new function

2023-06-07 12:27 UTC, littledivy approved these changes
LGTM!

2023-06-07 12:35 UTC, bartlomieju requested changes
We discussed this offline yesterday and we're not sure we want to do it. It actually breaks web compatibility for events emitted from WebSockets. We'll discuss it further before merging.

2023-06-25 07:38 UTC, bartlomieju commented
I'm gonna close this PR as we discussed other solutions to this problem and we are gonna explore them first.

2023-06-25 07:38 UTC, closed without merging