feat: Deno.createHttpClient allowHost
denoland/deno pull request #19689
Opened 2023-07-03 13:42 UTC by crowlKats

2023-07-03 14:34 UTC, andreubotella commented
You should also test that the header is sent, not just that it's exposed in the `Headers` object.

2023-07-03 14:42 UTC, lucacasonato commented on ext/fetch/26_fetch.js
> +    req.client.options.allowHost,
Instead of passing it in from JS to Rust on every call, just get/set it from the http client resource in Rust.

2023-07-04 17:22 UTC, aapoalas requested changes
Lint.

2023-07-04 17:54 UTC, aapoalas commented on ext/fetch/lib.rs
> +  let (client, allow_host) = if let Some(rid) = client_rid {
**comment:** This is the first time I see this sort of combination of `let` and `if let Some(X) = Y`. I am both in awe and appalled :D But, it makes sense after a while and was here before we got here so of course why not.

2023-07-10 10:51 UTC, lucacasonato approved these changes
Great. LGTM

2023-07-28 06:04 UTC, bartlomieju approved these changes

2023-07-28 07:01 UTC, merged