chore: try update deno_core
denoland/deno pull request #19897
Opened 2023-07-20 20:56 UTC by bartlomieju

## DO NOT MERGE

This is a test branch that applies necessary changes for updating `deno_core`
and running tests.

2023-07-20 21:03 UTC, mmastrac requested changes
Marking as request changes to prevent accidental merge

2023-07-21 11:49 UTC, andreubotella commented on runtime/web_worker.rs
> +      let context = realm.context();
`JsRuntime::global_context` was renamed to `main_context`, so you don't need to go through the realm.

2023-07-22 15:32 UTC, mmastrac reviewed
Looks good! Should we release deno_core and land?

2023-07-22 22:10 UTC, bartlomieju commented
> Looks good! Should we release deno_core and land?

Pending https://github.com/denoland/deno_core/pull/74

2023-07-23 13:01 UTC, bartlomieju commented
@mmastrac PTAL

2023-07-23 13:05 UTC, mmastrac approved these changes
LGTM

2023-07-23 13:42 UTC, merged