feat(unstable): Add `metadata` to `Deno.jupyter.broadcast`
denoland/deno pull request #20714
Opened 2023-09-27 18:43 UTC by manzt

- fix(cli): panic with __runtime_js_sources
- fix reassigning the namespace
- ensure fast ops, update test
- don't send reply if mime bundle is empty
- reset CI
- feat(unstable): add `metadata` to `Deno.jupyter.broadcast`.

Will rebase following merge of #20710 in to `main`.

Exposes [`metadata`](https://jupyter-client.readthedocs.io/en/latest/messaging.html#metadata) to the `Deno.jupyter.broadcast` API.

```js
await Deno.jupyter.broadcast(msgType, content, metadata);
```

The metadata is required for [`"comm_open"`](https://github.com/jupyter-widgets/ipywidgets/blob/main/packages/schema/messages.md#instantiating-a-widget-object-1) for with `jupyter.widget` target.
With this PR I can successfully communicate with the [`anywidget`](https://github.com/manzt/anywidget) frontend, sending frontend ESM via comms with updates :)

```javascript
import { display } from "https://deno.land/x/display/mod.ts";

let comm_id = crypto.randomUUID();

await Deno.jupyter.broadcast("comm_open", {
    "comm_id": comm_id,
    "target_name": "jupyter.widget",
    "data": { 
        "state": {
            "_model_module": "anywidget",
            "_model_name": "AnyModel",
            "_model_module_version": "0.6.5",
            "_view_module": "anywidget",
            "_view_name": "AnyView",
            "_view_module_version": "0.6.5",
            "_view_count": null,
        }
    }
}, {
    "version": "2.1.0"
});

// Create an anywidget module (export a "render" function) for the front end
// The `model` is synchronized with `update` messages sent from the comm_msg
let esm = `export ${async function render({ model, el }) {
  let { default: confetti } = await import ("https://esm.sh/canvas-confetti@1.6.0");
  model.on("change:value", () => confetti({ angle: model.get("value") }));
  confetti();
}.toString()}`;

// Send initial widget state
await Deno.jupyter.broadcast("comm_msg", {
    "comm_id": comm_id,
    "data": { "method": "update", "state": { "_esm": esm, "_anywidget_id": comm_id } }
});

display({
    "application/vnd.jupyter.widget-view+json": {
        "version_major": 2,
        "version_minor": 1,
        "model_id": comm_id,
    }
})
```

```javascript
await Deno.jupyter.broadcast("comm_msg", {
    "comm_id": comm_id,
    "data": { "method": "update", "state": { "value": 50 } },
});

await new Promise(resolve => setTimeout(resolve, 1000));

await Deno.jupyter.broadcast("comm_msg", {
    "comm_id": comm_id,
    "data": { "method": "update", "state": { "value": 100 } },
});

await new Promise(resolve => setTimeout(resolve, 1000));
```

This is sooo cool!!

2023-09-27 18:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno?pullRequest=20714) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno?pullRequest=20714) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: bartlomieju<br/>:white_check_mark: lucacasonato<br/>:x: manzt<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno?pullRequest=20714) it.</sub>

2023-09-27 18:46 UTC, manzt commented
cc: @rgbkrk

2023-09-27 18:51 UTC, manzt commented
I'm sure others are more familiar with the latest for how to serialize functions / modules to run clientside. Currently I have this hack:

```javascript
// Create an anywidget module (export a "render" function) for the front end
// The `model` is synchronized with `update` messages sent from the comm_msg
let esm = `export ${async function render({ model, el }) {
  let { default: confetti } = await import ("https://esm.sh/canvas-confetti@1.6.0");
  model.on("change:value", () => confetti({ angle: model.get("value") }));
  confetti();
}.toString()}`;
```

But anywidget, just expects you to ship ESM that exports a function called `render`. The render function gives you access to  a `model` which you can listen for and emit updates to state for objects that live in the kernel.

2023-09-27 20:59 UTC, manzt commented
https://github.com/denoland/deno/assets/24403730/c820fc93-05f7-4d80-9e02-be99eff566bb

2023-09-27 23:11 UTC, rgbkrk commented on cli/js/40_jupyter.js
> +    async broadcast(msgType, content, metadata = {}) {
👍  for optional metadata

2023-09-27 23:24 UTC, rgbkrk commented
This is awesome, I'm glad you were able to make this fly so quickly.

2023-09-27 23:52 UTC, rgbkrk commented
> Would be awesome to be able to listen for messages from the frontend as well (i.e. enabling 2-way data binding). Not sure that is implemented yet.

That's #20592. It would be nice to have the Javascript API for it that we want to expose that is as close to one of the many web standard options (to be Deno-y).

You're making me realize we probably need to support [`buffers`](https://jupyter-client.readthedocs.io/en/latest/messaging.html#buffers) as the final argument of this big broadcast message.

2023-09-28 14:01 UTC, manzt commented
>  It would be nice to have the Javascript API for it that we want to expose that is as close to one of the many web standard options (to be Deno-y).

Yes! I have some ideas.

> You're making me realize we probably need to support the [Jupyter message buffers](https://jupyter-client.readthedocs.io/en/latest/messaging.html#buffers) as the final optional argument of this big broadcast message.

Indeed.

The other option would be to have a single object for other possible message data.

```typescript
type DenoJupyter = typeof Deno & {
  jupyter: {
    broadcast(
      msg_type: string,
      content: { [key: string]: object },
      message?: {
        metadata?: Record<string, object>,
        buffers?: ArrayBuffer[]
      }
    ): Promise<void>;
  };
};
```

2023-09-28 14:52 UTC, bartlomieju commented
I just merged https://github.com/denoland/deno/pull/20710, can you please rebase the PR @manzt?

2023-09-28 14:58 UTC, rgbkrk commented
Famous last words and all, the jupyter spec will not extend the body of the message beyond content, metadata, and buffers.

I'm totally cool with `extra` though. 😄

2023-09-28 18:10 UTC, manzt commented
> I just merged https://github.com/denoland/deno/pull/20710, can you please rebase the PR @manzt?

Done, @bartlomieju! TIL `git cherry-pick`.

2023-09-28 19:29 UTC, bartlomieju requested changes
Looks great, could you please update `cli/tsc/dts/lib.deno.unstable.d.ts` to match the new JS API?

2023-09-28 20:44 UTC, manzt commented
done!

2023-09-29 17:43 UTC, manzt commented
Implemented a `mod.ts` in anywidget @rgbkrk . (Think I might have messed up the denoland webhooks, since it's a monorepo and I'm not sure how to specify release for the `packages/anywidget/mod.ts` path).

```ts
import { widget } from "https://raw.githubusercontent.com/manzt/anywidget/main/packages/anywidget/mod.ts";

let model = await widget({
    // shared model between frontend and backend
    state: { value: 0 },
    // front-end render function
    render: ({ model, el }) => {
        let h1 = Object.assign(document.createElement("h1"), {
            innerText: "Value is " + model.get("value"),
        });
        model.on("change:value", () => {
            h1.innerText = "Value is " + model.get("value");
        });
        el.appendChild(h1);
    }
});

model
```

```ts
for (let i = 1; i <= 10; i++) {
    model.set("value", i);
    await new Promise(resolve => setTimeout(resolve, 500));
}
```

2023-09-29 22:23 UTC, bartlomieju approved these changes
LGTM, thank you @manzt, great improvement and I can't wait to see what you'll be able to do with it!

2023-09-29 22:24 UTC, merged

2023-10-01 01:43 UTC, rgbkrk commented
Wrote a way to do imports with the anywidget in https://github.com/manzt/anywidget/pull/311