refactor: migrate more ops to op2 macro
denoland/deno pull request #20808
Opened 2023-10-05 22:59 UTC by bartlomieju

Getting closer...

2023-10-06 00:22 UTC, mmastrac commented on bench_util/benches/op_baseline.rs
>  // which is wrong, because i64 is not a compatible type for fast call.
```suggestion
```

2023-10-06 00:23 UTC, mmastrac approved these changes
LGTM one suggestion

2023-10-06 09:01 UTC, littledivy requested changes
I am not in favour of removing `op_encoding_encode_into_fallback`.

2023-10-06 09:01 UTC, littledivy commented on ext/web/lib.rs
> -  buffer: &mut [u8],
This is slower for non-latin-1 strings.

2023-10-06 11:41 UTC, mmastrac commented on ext/web/lib.rs
> -  buffer: &mut [u8],
Good point. I should implement this

2023-10-07 15:34 UTC, littledivy approved these changes
LGTM

2023-10-07 15:34 UTC, merged