refactor(ext/console): split code into functions
denoland/deno pull request #23274
Opened 2024-04-08 04:34 UTC by ArthurLobopro

I turned some parts of `cssToAnsi` into smaller functions to improve reading and maintenace

2024-04-08 04:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno?pullRequest=23274) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno?pullRequest=23274) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno?pullRequest=23274) it.</sub>

2024-04-08 04:48 UTC, ArthurLobopro commented
As you can see, I just turned some big parts of `cssToAnsi` into smaller functions that returns the ansi code. It's only an idea I had  while I was taking a look on the code.

2024-04-26 10:50 UTC, iuioiua requested changes

2024-04-26 15:52 UTC, ArthurLobopro commented
I thought about doing this, but I saw a lot of comparisons using == so I thought it was a lint rule or something like this

2024-07-18 13:55 UTC, closed without merging