feat: Upgrade to TypeScript 5.5.2 [WIP]
denoland/deno pull request #24326
Opened 2024-06-24 21:23 UTC by bartlomieju

2024-06-26 23:07 UTC, bartlomieju commented
Ref https://github.com/denoland/TypeScript/pull/12

2024-06-27 08:39 UTC, petamoriken requested changes

2024-06-27 08:39 UTC, petamoriken commented on cli/tsc/dts/lib.es2021.promise.d.ts
> +    withResolvers<T>(): { promise: Promise<T>; resolve: (value: T | PromiseLike<T>) => void; reject: (reason?: any) => void; };
This feature should be ES2024

2024-06-27 08:39 UTC, petamoriken commented on cli/tsc/dts/lib.webworker.d.ts
> -    bytes(): Promise<Uint8Array>;
Please remain 🙏

2024-06-27 08:39 UTC, petamoriken commented on cli/tsc/dts/lib.webworker.d.ts
> -    parse(url: string | URL, base?: string | URL): URL | null;
ditto

2024-06-27 09:34 UTC, petamoriken commented on cli/tsc/dts/lib.es2021.promise.d.ts
> +    withResolvers<T>(): { promise: Promise<T>; resolve: (value: T | PromiseLike<T>) => void; reject: (reason?: any) => void; };
As of TypeScript 5.5.2, it seems to be defined in [lib.esnext.promise.d.ts](https://github.com/microsoft/TypeScript/blob/v5.5.2/lib/lib.esnext.promise.d.ts). 

I work in progress to move this to lib.es2024.promise.d.ts.
https://github.com/microsoft/TypeScript/pull/58573

2024-07-02 22:43 UTC, bartlomieju reviewed
Thanks for the review @petamoriken, I reverted these changes.

2024-07-03 08:56 UTC, petamoriken requested changes

2024-07-03 08:56 UTC, petamoriken commented on cli/tsc/dts/lib.dom.d.ts
> +    canParse(url: string | URL, base?: string): boolean;
please fix 🙏

2024-07-03 08:56 UTC, petamoriken commented on cli/tsc/dts/lib.webworker.d.ts
> +    canParse(url: string | URL, base?: string): boolean;
ditto

2024-07-03 14:07 UTC, dsherret approved these changes
LGTM!

2024-07-03 14:09 UTC, merged

2024-07-03 18:46 UTC, petamoriken commented
I updated upstream types 😄
https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1755

2024-07-03 21:31 UTC, bartlomieju commented
Very cool, thanks!