feat(cli/test): improve test output readability (#24071)
denoland/deno pull request #24357
Opened 2024-06-27 13:49 UTC by hukuuu

Indent last line of tests that contain multiple steps.

2024-06-27 13:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno?pullRequest=24357) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno?pullRequest=24357) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno?pullRequest=24357) it.</sub>

2024-06-27 14:03 UTC, hukuuu commented
@iuioiua after a but of struggle i think i managed to fix this. Couple of things to note:

1) The implementation breaks when tests have "parallel steps" for example, in `cargo test test::steps_invalid_usage`:

```
Deno.test("parallel steps with sanitizers", async (t) => {
  // not allowed because steps with sanitizers cannot be run in parallel
  const step1Entered = Promise.withResolvers<void>();
  const testFinished = Promise.withResolvers<void>();
  t.step("step 1", async () => {
    step1Entered.resolve();
    await testFinished.promise;
  });
  await step1Entered.promise;
  await t.step("step 2", () => {});
});
```

Produces

```
parallel steps with sanitizers ...
  step 1 ... INCOMPLETE
    step 2 ... FAILED ([WILDCARD])
  parallel steps with sanitizers ... FAILED (due to incomplete steps) (3ms)
```

 I think its because of the `TestEvent`s not firing properly ( because of how the deno test is written, step 1 waits for step 2, which should be invalid thing. I made the cargo test pass by touching the .out file

2) We now indent tests that have only output ( and no nested steps ):

```
sync pass todo ...
------- output -------
Warning: Not implemented: test.TestContext.todo
----- output end -----
  sync pass todo ... ok (3ms)
```
I am not sure if this looks better or worse.


What are your thoughts?

2024-06-28 01:10 UTC, iuioiua requested changes
This doesn't seem like the correct approach. My understanding was that we just needed to prepend a couple of spaces, or increase `description.level` by 1, in the following lines:
https://github.com/denoland/deno/blob/8d14a9db2f0dd66492fadc498ae0070398d31d89/cli/tools/test/reporters/pretty.rs#L84
https://github.com/denoland/deno/blob/8d14a9db2f0dd66492fadc498ae0070398d31d89/cli/tools/test/reporters/pretty.rs#L361
Can you try that?

Also, looking at the output, I'm having 2nd thoughts on whether we should do the indent. Perhaps, just having the grayed text will suffice. Either way, let's see how it all looks 🙂

2024-06-29 20:45 UTC, hukuuu commented
Following your suggestion verbatim doesnt produce the desired result. Couple of screenshots ( i have put an x in front just to make things easier to see )

<img width="576" alt="image" src="https://github.com/denoland/deno/assets/1475500/bbe1581a-1816-4e9b-aad8-83a090f9c461">

<img width="619" alt="image" src="https://github.com/denoland/deno/assets/1475500/47e53266-dfc2-4118-ae3c-fb0620228b83">

Here is the test output of an example project i use to test this:

<img width="810" alt="image" src="https://github.com/denoland/deno/assets/1475500/734df9ee-8c30-4052-9b4a-417dad694aa6">

There are two problems here:
1) My understanding is that tests and steps should be indented if they have children. With your suggestion only steps are being prefixed.
2) All steps are being indented, instead of only those who have nested steps

-- 

I think we must have a condition to understand wether a test/step is actually a parent. My best try to infer that is to see whether we are in a new line while printing the result. If the test/step doesnt have children, its result will be printed at the same line as the description ( `self.is_new_line` is false ). Conversely, if `self.is_new_line` is true, that means that the test/step in question is resuming the printing after its children have finished printing.

Maybe, another way to infer the same would be to peek at the `child_results_buffer` lenght

Also, even just to make things grey, i think the same inference should happen

2024-07-05 15:23 UTC, nkaradzhov commented
@iuioiua Did you have time to look at this?

2024-07-14 08:31 UTC, iuioiua commented
Sorry, not yet. I will this week 🙂

2024-08-25 11:08 UTC, nkaradzhov commented
@iuioiua shall we close this one or do you still think its useful?

2024-08-28 05:34 UTC, iuioiua commented
Sorry again for the delay. I've pinged some of the team to gather their thoughts on the change to see if they're in favor.

2025-01-05 18:36 UTC, nkaradzhov commented
Hi @iuioiua happy new year! Any news on this one?

2025-01-11 09:32 UTC, iuioiua commented
Hey, sorry for letting this slip. Seeing it's been so long, I now whether there's sufficient support to continue pursuing this change. WDYT, @marvinhagemeister?

2025-05-06 21:29 UTC, bartlomieju requested changes
I'm inclined to close this for now as we will be working on better compatibility for node:test and will most likely improve the output of the test runner.

2025-05-08 21:12 UTC, bartlomieju commented
Gonna close this one for now, we'll revisit the output of test framework soon.

2025-05-08 21:12 UTC, closed without merging