feat: add `Deno.ConfigFile`
denoland/deno pull request #24630
Opened 2024-07-18 00:58 UTC by iuioiua

Note: this hasn't yet reached consensus.

Closes #24628

2024-07-18 01:00 UTC, iuioiua commented on cli/tsc/dts/lib.deno.ns.d.ts
> +   * files provide file-based type-hinting and autocompletion anyway.
I should be fact-checked on this, namely if the wording is accurate. These are based on what I found on my machine.

2024-07-18 01:00 UTC, iuioiua commented on cli/tsc/dts/lib.deno.ns.d.ts
> +  // https://transform.tools/json-schema-to-typescript
Naturally, the question would arise: how do we keep this interface up-to-date?

2024-07-18 03:04 UTC, dsherret requested changes
I'm against this: https://github.com/denoland/deno/issues/24628#issuecomment-2235217031

2024-07-18 03:05 UTC, dsherret commented on cli/tsc/dts/lib.deno.ns.d.ts
> +  export interface ConfigFile {
This would be good to publish on JSR. For example, someone could generate this type from the deno schema file and have it behind a versioned API.

2024-09-03 03:48 UTC, iuioiua commented
Closing as I think there's insufficient demand for this.

2024-09-03 03:48 UTC, closed without merging