refactor(ext/fs): remove some uses of #[serde]
denoland/deno pull request #24810
Opened 2024-07-31 13:10 UTC by lucacasonato

2024-07-31 21:06 UTC, nathanwhit commented on ext/fs/30_fs.js
> +    options?.read ?? true,
```suggestion
    options?.read ?? false,
```
And likewise below

2025-04-15 19:44 UTC, dsherret requested changes
I think there's a breaking change in this, but please confirm. It causes a node compat test to fail.

2025-04-15 19:44 UTC, dsherret commented on ext/fs/30_fs.js
> +  }
Is this a breaking change?

```suggestion
```

2025-05-09 00:52 UTC, ry commented
closing because old

2025-05-09 00:52 UTC, closed without merging