ci: fix 'promote_to_rc' workflow
denoland/deno pull request #25074
Opened 2024-08-16 22:42 UTC by bartlomieju

Just a simple typo :)

2024-08-16 22:43 UTC, dsherret approved these changes

2024-08-16 23:06 UTC, bartlomieju commented
Found one last problem - need to re-sign the Mac binaries.

2024-08-17 02:58 UTC, littledivy approved these changes
LGTM

2024-08-17 02:59 UTC, littledivy requested changes

2024-08-17 02:59 UTC, littledivy commented on tools/release/promote_to_rc.ts
> +  await runRcodesign(target, rcBinaryName);
Oh I forgot this: only sign the `deno` binary. `denort` is strippped of signatures anyways during `deno compile`

2024-08-17 16:50 UTC, littledivy approved these changes

2024-08-18 20:45 UTC, merged