fix(ext/node): prevent early stdin closure
denoland/deno pull request #25124
Opened 2024-08-21 04:06 UTC by littledivy

Fixes `npm-run-all` compat.

Fixes https://github.com/denoland/deno/issues/24425

2024-10-24 19:13 UTC, hectorm commented
I can confirm that this addresses the issue.

2024-10-24 19:21 UTC, bartlomieju approved these changes

2025-04-15 19:21 UTC, dsherret requested changes
Seems to break a test.

2025-05-07 05:29 UTC, littledivy commented
Stale. Closing.

2025-05-07 05:29 UTC, closed without merging