fix(node): use referrer to determine *.d.ts script kind
denoland/deno pull request #25484
Opened 2024-09-06 10:49 UTC by nayeemrmn

Fixes #24451.
Fixes #25359.

2024-09-06 11:30 UTC, dsherret requested changes
The fix here is not exactly correct. I think the problem here is that some packages will have package.json exports that lead to a .d.ts file that is in a position that makes it cjs, but it should be treated as esm? I think we need a way to figure out when that happens for .d.ts files only, which will make our node resolution more complicated. I think it requires a refactor of ext/node_resolution/resolver.rs to essentially do `url_to_node_resolution` at a lower level.

2024-09-06 11:30 UTC, dsherret commented on ext/node/ops/worker_threads.rs
> +    _ => Err(generic_error("Neither ESM nor CJS")),
Can you revert this to not use a wildcard pattern match? When we add or change variants on `NodeResolution` we should get a compiler error here.

2024-09-06 11:30 UTC, dsherret commented on tests/specs/check/cjs_default_export/main.out
> +export const Test: string = cjsDefault();
This should be `cjsDefault.default()` for ESM importing CJS.

2024-09-07 05:12 UTC, nayeemrmn commented
I tried the various reproductions which spurred this patch again under Node/TS, this time remembering to add `{ "type": "module" }` in `package.json` and using the following Deno-like tsconfig:
```json
{
  "compilerOptions": {
    "allowJs": true,
    "esModuleInterop": true,
    "experimentalDecorators": false,
    "isolatedModules": true,
    "lib": ["esnext"],
    "module": "nodenext",
    "moduleDetection": "force",
    "noEmit": true,
    "resolveJsonModule": true,
    "strict": true,
    "target": "esnext",
    "useDefineForClassFields": true,
    "jsx": "react",
    "jsxFactory": "React.createElement",
    "jsxFragmentFactory": "React.Fragment",
    "types": ["@types/node"],
  },
}
```
It turns out that none of them are behaving wrong. All of them behave the same as tsc for both the diagnostics shown and the emit/execution. I'll follow up in the issues. Closing.

2024-09-07 05:12 UTC, closed without merging