ci: make uploading canary less racy, take 2
denoland/deno pull request #25751
Opened 2024-09-19 23:55 UTC by bartlomieju

Another try at https://github.com/denoland/deno/issues/25464
using a Deno script.

2024-09-20 03:42 UTC, littledivy approved these changes

2025-04-15 19:47 UTC, dsherret requested changes
See comment. Currently out of date.

2025-04-15 19:47 UTC, dsherret commented on .github/workflows/ci.generate.ts
> +            "./tools/release/upload_canary.ts arch ${{ github.sha }}",
There's been some changes on main since this PR to add the shasums and symcache:

https://github.com/denoland/deno/blob/3071aa2759a6092fcd56b06eee63303aa3425df0/.github/workflows/ci.generate.ts#L863-L867

2025-05-08 17:52 UTC, dsherret approved these changes
LGTM

2025-05-08 19:04 UTC, merged