fix: resolve shebang parse error in deno doc --test
denoland/deno pull request #26079
Opened 2024-10-09 14:02 UTC by MujahedSafaa

This PR addresses the issue reported in https://github.com/denoland/deno/issues/26018.

Issue:
Running deno doc --test on a file that contains a shebang results in a parse error.

Solution:
The bug has been fixed by updating the regex to ensure that the shebang characters (#!) are no longer excluded. This allows the shebang to be retained and parsed correctly.

2024-10-28 01:03 UTC, magurotuna requested changes
Looks good!
One request though: could you add a test case for a doc test written in markdown? Something like:

````markdown
# my-awesome-readme

This is a markdown file.

```ts
#!/usr/bin/env -S deno run --allow-read
import { assertEquals } from "@std/assert/equals";
assertEquals(1 + 2, 3);
```

````

2024-11-15 09:51 UTC, bartlomieju commented
@MujahedSafaa could you please add a test as pointed above so we can land this PR?

2025-04-15 20:30 UTC, dsherret commented on cli/util/extract.rs
> +    lazy_regex::regex!(r"^(?:\* ?((#!+).*)|(?:\* ?(?:# ?)?(.*)))$");
I just updated this and it's incorrect. I'll fix it soon.

2025-04-16 04:54 UTC, magurotuna approved these changes
LGTM 👍

2025-04-16 04:56 UTC, merged