feat(ext/node): implements more dgram compatibility APIs
denoland/deno pull request #26452
Opened 2024-10-21 18:47 UTC by cemelo

Affects #18324, although it doesn't implement all the missing functionality there. This one changes how multicast membership is created on IPv6 to match the same behavior that Node.js has.

I added the bare minimum required to run https://github.com/project-chip/matter.js over Deno.

2024-10-21 18:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno?pullRequest=26452) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno?pullRequest=26452) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno?pullRequest=26452) it.</sub>

2024-11-26 12:01 UTC, kt3k commented
Looks in a good direction to me.

Can you write some simple test cases of `setBroadcast`, `dropMulticastV4`, and `dropMulticastV6` of `DatagramConn` class in `tests/unit/net_test.ts`?

Also can you write test cases of `setBroadcast`, `addMembership`, and `dropMembership` of `dgram.Socket` class (`node:dgram`) in `tests/unit_node/dgram_test.ts`?

2025-05-07 04:40 UTC, littledivy requested changes

2025-05-07 04:40 UTC, littledivy commented on ext/node/polyfills/internal_binding/udp_wrap.ts
> +    return 0;
This should return an error code when `setBroadcast` fails

2025-06-20 06:54 UTC, Apollon77 commented
Hey, its there any chance to get this finished ... and maybe also add "set/dropMulticastInterface"? This would be (at least from now seeing) the main things needed to have "matter,js" (the JavaScript Matter implementation) also run via Deno and to see if this could get less RAM usage or such.
See also https://github.com/project-chip/matter.js/discussions/1712

2025-06-23 09:13 UTC, anonhostpi commented
> Hey, its there any chance to get this finished ... and maybe also add "set/dropMulticastInterface"? This would be (at least from now seeing) the main things needed to have "matter,js" (the JavaScript Matter implementation) also run via Deno and to see if this could get less RAM usage or such. See also [project-chip/matter.js#1712](https://github.com/project-chip/matter.js/discussions/1712)

From the author's contribution history, this PR may need to be picked up by another member of the community.

Looks like the author has been entirely focused on work contributions (all private repo contributions) for the last 8 months and probably dropped the PR entirely.

2026-03-12 10:19 UTC, bartlomieju commented
Closing since this is stale and I opened several PRs recently that improved the compatibility. Thanks!

2026-03-12 10:19 UTC, closed without merging