fix(compile): improve handling of Windows junctions and symbolic links
denoland/deno pull request #26487
Opened 2024-10-23 12:13 UTC by yazan-abdalrahman

fix #26316

2024-10-23 12:14 UTC, yazan-abdalrahman commented
@dsherret Please can review this change.

2024-10-25 01:55 UTC, dsherret requested changes
I've been trying to reproduce this and I'm not sure this is the issue. Have you been able to create a reproduction? Is there a test you know of that fails on main?

2024-10-25 01:55 UTC, dsherret commented on cli/standalone/virtual_fs.rs
> +  fn resolve_symlinks_in_path(
Can you explain what this function does? I'm having trouble following it.

2024-10-25 01:55 UTC, dsherret commented on cli/standalone/virtual_fs.rs
> +    #[cfg(windows)]
Why should we only do this for Windows?

2024-10-25 02:47 UTC, dsherret commented
I investigate this one and it's already fixed on main via the changes in (https://github.com/denoland/deno/pull/26494 which surfaced this bug more readily).

That said, I don't believe this is the right fix for this issue and I don't understand the code in the PR (I'm not sure why it's so complex). Instead of doing this, we can instead ignore adding a symlink/junction when the newpath is outside the root directory (which is what #26494 did). Maybe in the future we could have some way to have a root that is above multiple windows drives, but for the time being having the restriction that all the files must live under a link to a different drive is not too bad.

2024-10-25 02:47 UTC, closed without merging

2024-10-27 06:46 UTC, yazan-abdalrahman commented
> I investigate this one and it's already fixed on main via the changes in (#26494 which surfaced this bug more readily).
> 
> That said, I don't believe this is the right fix for this issue and I don't understand the code in the PR (I'm not sure why it's so complex). Instead of doing this, we can instead ignore adding a symlink/junction when the newpath is outside the root directory (which is what #26494 did). Maybe in the future we could have some way to have a root that is above multiple windows drives, but for the time being having the restriction that all the files must live under a link to a different drive is not too bad.

THX,
Sure, ignoring symlink is easier.


In this scenario, my method attempts to canonicalize the path until it matches the canonicalized root. However, if there are multiple symlinks, the root can be canonicalized until the last symlink, which can cause issues. Therefore, this dynamic method resolves each symlink one by one until the root and path match.