fix: enhance hints for bare Node.js built-in modules
denoland/deno pull request #26669
Opened 2024-11-01 00:17 UTC by bartlomieju

The hint was not helpful in all situations as it didn't list the
`--unstable-bare-node-builtins` flag or the `bare-node-builtins`
option in the `unstable` config.

2024-11-01 15:32 UTC, dsherret approved these changes
LGTM

2024-11-01 17:25 UTC, bartlomieju commented on cli/graph_util.rs
> +        --unstable-bare-node-builtins flag, or specify `bare-node-builtins` in the `unstable` option in the config file."))
This should actually be reverted, because it's only shown when the flag is present

2025-04-15 21:30 UTC, dsherret requested changes
I think something went wrong since approval (maybe with a merge). There seems to be a lot of unrelated changes.

2025-05-06 21:38 UTC, bartlomieju commented
I don't think this is actually needed, the warning are now gone.

2025-05-06 21:38 UTC, closed without merging