fix(publish): continue publishing with errors
denoland/deno pull request #26829
Opened 2024-11-12 11:38 UTC by littledivy

In a workspace of two packages A and B, failure during publishing of package B can lead to provenance step being skipped of package A. This PR makes it prints out the error and continue publishing other packages instead of a fast fail.

2024-11-12 11:51 UTC, lucacasonato commented
Please make sure we still exit with code 1 at the end.

2024-11-12 13:02 UTC, lucacasonato approved these changes, later dismissed

2024-11-12 13:03 UTC, lucacasonato commented
Actually, I am not sure this works. Doesn't the `.next()` function that gets the next batch of packages just get stuck when any module fails?

2024-11-12 23:44 UTC, dsherret requested changes
> In a workspace of two packages A and B, failure during publishing of package B can lead to provenance step being skipped of package A.

It sounds like we should change the code so that the provenance is verified after publish of package A before moving on to package B.

Also, what issue is this fixing? It would be good to add a test to demonstrate the fix and show the problem.

2024-12-18 07:26 UTC, kt3k commented
This fixes https://github.com/denoland/std/issues/6133

2026-06-10 09:16 UTC, bartlomieju commented
Closing in favor of #35091, which describes the problem to fix. This PR has gone stale and conflicts with `main` (the relevant code moved from `cli/tools/registry/mod.rs` to `cli/tools/publish/mod.rs`).

2026-06-10 09:16 UTC, closed without merging