fix(ext/node): process.getBuiltinModule
denoland/deno pull request #26833
Opened 2024-11-12 13:42 UTC by littledivy

Closes https://github.com/denoland/deno/issues/26832

2024-11-12 13:59 UTC, bartlomieju approved these changes

2024-11-12 15:07 UTC, nicolo-ribaudo commented on ext/node/polyfills/01_require.js
> +Module.getBuiltinModule = getBuiltinModule;
`Module.getBuiltinModule` does not exist in Node.js

2024-11-12 16:29 UTC, bartlomieju requested changes
https://github.com/denoland/deno/pull/26833/files#r1838268827

2024-11-12 16:29 UTC, bartlomieju commented on tests/unit_node/process_test.ts
> +  assertEquals(process.getBuiltinModule("something"), undefined);
Actually please add a test that uses `node:fs` too

2024-11-13 02:32 UTC, merged

2024-11-13 08:18 UTC, nicolo-ribaudo commented
Thank you! :)