fix(fmt): stable formatting of HTML files with JS
denoland/deno pull request #27164
Opened 2024-11-30 02:34 UTC by bartlomieju

Closes https://github.com/denoland/deno/issues/26407
Closes https://github.com/denoland/deno/issues/26763
Closes https://github.com/denoland/deno/issues/26560
Closes https://github.com/denoland/deno/issues/26744

2024-11-30 02:37 UTC, bartlomieju commented
This still is broken. 

For all three reproductions I get `indent_level` of 0 coming from `markup_fmt`.

2024-12-02 13:42 UTC, g-plane commented
markup_fmt v0.18.0 is released.

Notes:

- It also fixes #27030 .
- New option `script_formatter` is introduced. For Deno, its value should be `Some(ScriptFormatter::Dprint)`.

2024-12-02 13:49 UTC, bartlomieju commented
Thanks! Will try it out tonight.

2024-12-02 17:14 UTC, dsherret commented on cli/tools/fmt.rs
> +  Ok(Some(formatted_str))
I think this should be reverted? Was there no test that fails?

2024-12-02 17:14 UTC, dsherret commented on cli/tools/fmt.rs
> +  Ok(Some(formatted_str))
https://github.com/denoland/deno/pull/27014/files#diff-fe46255b8864b7c270c3f211fd444d65e0290b72bdf1bc5aff9c1198c3576ff2

2024-12-02 17:27 UTC, marvinhagemeister approved these changes

2024-12-02 17:28 UTC, dsherret requested changes
Going to block this one until https://github.com/denoland/deno/pull/27187 is resolved

2024-12-02 22:24 UTC, dsherret approved these changes
LGTM

2024-12-03 01:04 UTC, merged