fix(std/testing): assertion diff color
denoland/deno pull request #7499
Opened 2020-09-15 15:02 UTC by g-plane

Before:
![图片](https://user-images.githubusercontent.com/17216317/93227804-5a038280-f7a7-11ea-9326-3eb788537f11.png)

After:
![图片](https://user-images.githubusercontent.com/17216317/93227939-85866d00-f7a7-11ea-902a-354d198196b8.png)

2020-09-15 15:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno?pullRequest=7499) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno?pullRequest=7499) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno?pullRequest=7499) it.</sub>

2020-09-15 15:13 UTC, nayeemrmn requested changes
Have you tried putting the `stripColor` around the `Deno.inspect()` call instead?

L24-L30:
```diff
-     ? Deno.inspect(v, {
+     ? stripColor(Deno.inspect(v, {
        depth: Infinity,
        sorted: true,
        trailingComma: true,
        compact: false,
        iterableLimit: Infinity,
-     })
+     }))
```

2020-09-15 15:16 UTC, g-plane commented
@nayeemrmn Applied.

2020-09-15 15:17 UTC, nayeemrmn commented on std/testing/asserts.ts
> +      return (s: string): string => white(s);
Revert.

2020-09-15 15:43 UTC, nayeemrmn approved these changes
LGTM 👍

2020-09-16 10:42 UTC, bartlomieju approved these changes
LGTM, thanks @g-plane

2020-09-16 10:42 UTC, merged