add importmap file to be watched
denoland/deno pull request #7580
Opened 2020-09-19 12:16 UTC by bartOssh

Fixes [#7519](https://github.com/denoland/deno/issues/7519)

2020-09-22 15:26 UTC, bartlomieju requested changes

2020-09-22 15:26 UTC, bartlomieju commented on cli/import_map.rs
>    fn try_url_like_specifier(specifier: &str, base: &str) -> Option<Url> {
This bit is not needed

2020-09-22 15:26 UTC, bartlomieju commented on cli/main.rs
> +  }
Try using `global_state.flags.import_map_path`

2020-09-23 08:28 UTC, bartOssh commented
revert was a mistake, cleaned

2020-09-23 11:55 UTC, bartlomieju approved these changes
LGTM, thanks @bartOssh

2020-09-23 11:56 UTC, merged