refactor(cli/inspector): make server optional
denoland/deno pull request #7656
Opened 2020-09-24 13:47 UTC by caspervonb

This makes inspector registration with the server with optional and explicit to allow for inspectors to exist without spinning up the server.

As a side effect of the server being explicitly passed around it also makes it possible to bind multiple servers.

2020-09-24 14:04 UTC, caspervonb commented
Ties into #7473

2020-09-24 14:33 UTC, bartlomieju commented
@caspervonb so `--coverage` will not print `Debugger listening on...` message?

2020-09-24 14:37 UTC, caspervonb commented
> @caspervonb so --coverage will not print Debugger listening on... message?

In a follow up will, this only makes the two separable but doesn't change the behaviour of current flags configuration/parsing.

2020-09-24 16:00 UTC, bartlomieju requested changes

2020-09-24 16:00 UTC, bartlomieju commented on cli/worker.rs
> +        })
This call will result in multiple servers being created

2020-09-25 08:24 UTC, bartlomieju approved these changes
LGTM, nice cleanup @caspervonb

2020-09-25 08:24 UTC, merged