fix(cli/rt/websockets): Only add Sec-WebSocket-Protocol if it's not empty
denoland/deno pull request #7936
Opened 2020-10-11 14:55 UTC by Nerixyz

This issue fixes #7935 . The `WebSocket` will only add the header if it's not empty.

2020-10-11 14:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno?pullRequest=7936) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno?pullRequest=7936) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno?pullRequest=7936) it.</sub>

2020-10-11 19:54 UTC, bartlomieju requested changes
Thanks @Nerixyz, can you add a test case?

@crowlKats please take a look

2020-10-11 20:12 UTC, crowlKats commented
Just noticed another small mistake with protocols: protocols on the JS side are joined by `; `, but while checking the spec for this PR i noticed that it should be `, `. @Nerixyz could you add this change to this PR as well?
That aside, LGTM.

2020-10-11 20:13 UTC, Nerixyz commented
@bartlomieju Sure, I'd like to add tests, but I don't really know where to test this.

2020-10-11 20:17 UTC, bartlomieju commented
> @bartlomieju Sure, I'd like to add tests, but I don't really know where to test this.

@Nerixyz `WebSocket` unit tests are in `cli/tests/websocket_test.ts`

2020-10-11 20:26 UTC, Nerixyz commented
> `WebSocket` unit tests are in `cli/tests/websocket_test.ts`

@bartlomieju I know WebSocket tests are there, but I don't know a way of testing the protocol header.

2020-10-12 10:49 UTC, bartlomieju commented
@crowlKats could you point @Nerixyz where this could be tested?

2020-10-12 10:52 UTC, crowlKats commented
@bartlomieju this is the same problem as #7606 where we need a server to test such case, which isnt really the easiest thing to do.

2020-10-13 22:43 UTC, Nerixyz commented
For this test we'd need a strict WebSocket server which rejects/closes invalid handshakes. `tungstenite-rs` however doesn't negotiate protocols at all.

2020-10-16 19:57 UTC, Nerixyz commented
@bartlomieju Could you merge this pr and then maybe create an issue regarding the testing of the WebSocket implementation.

2020-10-22 15:09 UTC, bartlomieju approved these changes
LGTM, not very happy to merge a PR without a tests, but it seems there's no obvious way to test this

2020-10-22 15:09 UTC, merged