refactor: replace `String` with `path::PathBuf` for lint and fmt subcommands
denoland/deno pull request #8042
Opened 2020-10-20 00:06 UTC by humancalico

There was not really a need for this PR but it was a pain to work with files with `String`s as you have to convert them every time you need to use them. So I went ahead and replaced the `String`s with `PathBuf`s (for the Lint and Fmt subcommands)

2020-10-20 11:10 UTC, bartlomieju requested changes

2020-10-20 11:10 UTC, bartlomieju commented on cli/flags.rs
> +          ], // TODO(humancalico) maybe create a PathBuf macro like svec
remove the TODO, I don't think a macro is needed

2020-10-20 11:10 UTC, bartlomieju commented on cli/fmt.rs
> +  if args.len() == 1 && args.get(0).unwrap().to_str().unwrap() == "-" {
`args[0].display()`?

2020-10-20 11:10 UTC, bartlomieju commented on cli/lint.rs
> +  if args.len() == 1 && args.get(0).unwrap().to_str().unwrap() == "-" {
`args[0].display()`

2020-10-20 11:10 UTC, bartlomieju commented on cli/fmt.rs
> +          .extend(files_in_subtree(arg.canonicalize()?, is_supported));
rename `arg` to `file`

2020-10-20 15:04 UTC, humancalico commented on cli/fmt.rs
> +  if args.len() == 1 && args.get(0).unwrap().to_str().unwrap() == "-" {
Getting this error on using this
```rust
binary operation `==` cannot be applied to type `std::path::Display<'_>`
```

2020-10-20 22:30 UTC, bartlomieju requested changes

2020-10-20 22:30 UTC, bartlomieju commented on cli/lint.rs
> +    // TODO don't use unwrap here
this TODO is outdated

2020-10-21 11:11 UTC, bartlomieju approved these changes
LGTM, thanks @humancalico

2020-10-21 11:12 UTC, merged