BREAKING(cli/tsc): Enable isolatedModules by default
denoland/deno pull request #8050
Opened 2020-10-20 15:07 UTC by nayeemrmn

Closes #7326.

Closes #7947, as code written for stable is once again compatible with `--unstable`. Discussion: I strongly feel we should maintain this property, even if it means going straight to stable for future changes like this. Code written for `--unstable` is by design incompatible with stable -- having incompatibilities going the opposite way as well splits the ecosystem in half, generating a lot of headache and noise. Better to have everyone adapt at once.

2020-10-20 19:43 UTC, kitsonk commented
I am in the process of #7225 and specifically #7996 this week, which also address this.  It is best to avoid any other PRs in this area for now.

2020-10-20 19:47 UTC, nayeemrmn commented
Okay, thanks.

2020-10-23 00:50 UTC, kitsonk commented
It can be rebased now.

2020-10-23 01:25 UTC, kitsonk requested changes
This is insufficient, as `cli/tsc.rs` will be retired after #8059 and #8060 are resolved (likely tomorrow).  We need to update [module_graph2.rs](https://github.com/denoland/deno/blob/master/cli/module_graph2.rs#L711) as well.

2020-10-23 01:54 UTC, kitsonk approved these changes
LGTM, but I going to leave it for @bartlomieju to merge in light of coordinating other things regarding the 1.5 release.

2020-10-23 10:38 UTC, bartlomieju approved these changes
LGTM

2020-10-23 10:38 UTC, merged