remvoe unnecessary if else block
denoland/deno pull request #8321
Opened 2020-11-09 21:04 UTC by behnammodi

In the title is explained :)

2020-11-09 21:53 UTC, kitsonk requested changes
You need to make changes in order to have CI pass.

2020-11-09 21:53 UTC, kitsonk commented on std/fs/ensure_symlink.ts
> +  const options = Deno.build.os === "windows"
```suggestion
  const options: Deno.SymlinkOptions = Deno.build.os === "windows"
```

2020-11-09 21:53 UTC, kitsonk commented on std/fs/ensure_symlink.ts
> +  const options = Deno.build.os === "windows"
```suggestion
  const options: Deno.SymlinkOptions = Deno.build.os === "windows"
```

2020-11-09 22:20 UTC, behnammodi commented
@kitsonk Thank you, I did it, I'm very enjoying this project, It's awesome :)

2020-11-10 04:38 UTC, kitsonk approved these changes
LGTM

2020-11-10 04:38 UTC, merged

2020-11-12 02:52 UTC, nurmohammed840 commented
I have a question in code snippet, please read the comments below... 
```ts
export async function ensureSymlink(src: string, dest: string): Promise<void> {
	const srcStatInfo = await Deno.lstat(src);  // 1. what is the point to `wait` here!?
	const srcFilePathType = getFileInfoType(srcStatInfo);  // I mean `srcFilePathType` would or could remain unused!

	if (await exists(dest)) {   // because  if this code block run then `ensureSymlink` will ether  throw 'err' or return 'undefiend'
		const destStatInfo = await Deno.lstat(dest);
		const destFilePathType = getFileInfoType(destStatInfo);
		if (destFilePathType !== "symlink") {
			throw new Error(`Ensure path exists, expected 'symlink', got '${destFilePathType}'`);
		}
		return;  
	}

	await ensureDir(path.dirname(dest)); 

+     const srcStatInfo = await Deno.lstat(src);  // those code line should belong here. 
+     const srcFilePathType = getFileInfoType(srcStatInfo); 

	const options: Deno.SymlinkOptions | undefined = isWindows
		? { type: srcFilePathType === "dir" ? "dir" : "file" } // even though  `srcFilePathType` read here only!
		: undefined;

	await Deno.symlink(src, dest, options);
}
```
Am I right ?

2020-11-13 12:39 UTC, behnammodi commented
@nurmohammed840 I fixed thank you 👏🏻