fix(window) fix onload event order
denoland/deno pull request #8376
Opened 2020-11-13 18:35 UTC by benjamingr

Deno has a bug where it currently always attaches `.onload` before `addEventListener` see [this](http://jsbin.testim.io/wer/1/edit?html,js,output) for a web example.

The following code:
```js
let arr: any = [];
window.addEventListener('load', () => {
  arr.push(1);
});
window.onload = () => arr.push(2);
window.addEventListener('load', () => {
  arr.push(3);
});

window.addEventListener('load', () => {
  setTimeout(() => {
    console.log(arr);
  })
})
```

Logs `[ 2, 1, 3 ]` in deno whereas browsers (and deno with this patch) log `[ 1, 2, 3 ]`

Note that this can be a relatively risky change compared to the AbortSignal/WebSocket/Worker timing fixes

2020-11-21 18:34 UTC, bartlomieju requested changes

2020-11-21 18:34 UTC, bartlomieju commented on cli/rt/99_main.js
> +    }
It seems this code can be obtained using `const { defineEventHandler } = window.__bootstrap.webUtil;`

2020-11-26 12:55 UTC, bartlomieju approved these changes
LGTM, thanks @benjamingr

2020-11-26 13:10 UTC, benjamingr commented
Thanks, sorry I'm a bit sick (and on my phone and not computer) - note that de-duplication here means that we return `undefined` and not `null` for things like `onload` which _probably_ needs a separate fix.

2020-11-26 13:12 UTC, bartlomieju commented
> Thanks, sorry I'm a bit sick (and on my phone and not computer) - note that de-duplication here means that we return `undefined` and not `null` for things like `onload` which _probably_ needs a separate fix.

@benjamingr thanks for pointing this out, should we hold on before merging then?

2020-11-26 15:10 UTC, benjamingr commented
> @benjamingr thanks for pointing this out, should we hold on before merging then?

I think merging is probably fine it's an improvement I will follow up with another fix

2020-11-26 21:27 UTC, merged