feat: Added os.type pollyfill for Node std library
denoland/deno pull request #8591
Opened 2020-12-02 17:14 UTC by MVEMCJSUNPE

Should check off os.type in #3802 . I know that there's already been work done by @jbergstroem on os.type in this [pull request](https://github.com/jbergstroem/deno/commit/b7b690ba6149dc701b5cb843bbec5b03c49e6c57) first, but for some reason a pull request wasn't submitted. If @jbergstroem wants to come forward and have his solution used, then I would be happy to oblige.

2020-12-02 17:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno?pullRequest=8591) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno?pullRequest=8591) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno?pullRequest=8591) it.</sub>

2020-12-02 18:36 UTC, jbergstroem commented
> . If @jbergstroem wants to come forward and have his solution used, then I would be happy to oblige.

I context switched to other stuff and didn't follow up properly. Appreciate someone taking up the torch and crossing the goal line!

2020-12-04 09:19 UTC, bnoordhuis approved these changes
LGTM but the CI seems to think there's still a lint error somewhere.

2020-12-04 23:14 UTC, MVEMCJSUNPE commented
I'm kind of stuck on where the lint error could be. From the error output, it seems like 'git status' is complaining?
```
2020-12-02T23:34:28.1997398Z dprint
2020-12-02T23:34:30.0319239Z rustfmt 103 file(s)
2020-12-02T23:34:31.4525905Z run tools/format.js
2020-12-02T23:34:31.4526506Z  M cli/ops/os.rs
```
This output corresponds to the lines in 'tools/format.js':
https://github.com/denoland/deno/blob/71ef5a9cd33390f7f41b80cdb57862b7f7507f76/tools/format.js#L38-L62

From looking at the code, it seems that 'git status' shouldn't be outputing anything.

2020-12-04 23:30 UTC, bartlomieju commented
@MVEMCJSUNPE make sure to have latest stable Rust toolchain installed (1.48.0)

2020-12-04 23:37 UTC, MVEMCJSUNPE commented
I'm pretty sure that's the version I have:
```sh
> rustc --version
rustc 1.48.0 (7eac88abb 2020-11-16)
```

2020-12-05 15:08 UTC, bartlomieju commented
@MVEMCJSUNPE what's the version of `rustfmt` you're using? It should be `rustfmt 1.4.24-stable (eb894d53 2020-11-05)`

2020-12-05 15:11 UTC, MVEMCJSUNPE commented
My rustfmt version:
```sh
> rustfmt --version
rustfmt 1.4.24-stable (eb894d5 2020-11-05)
```

2020-12-05 15:13 UTC, bartlomieju commented
@MVEMCJSUNPE I'm not sure what's the problem, I'll reformat the code for you

2020-12-05 15:15 UTC, MVEMCJSUNPE commented
Thanks @bartlomieju

2020-12-05 19:47 UTC, MVEMCJSUNPE commented
For some reason, the license/cla is still pending even though I thought I signed it?

2020-12-06 17:01 UTC, ry reviewed
I don't think it's necessary to add a new op for this:
```
> deno eval -p Deno.build.os
linux
```

2020-12-06 17:27 UTC, MVEMCJSUNPE commented
Now that @ry has mentioned Deno.build.os, I kind of agree. The only situation where I think that Deno.build.os might not be sufficient is if someone is [cross compiling](https://en.wikipedia.org/wiki/Cross_compiler) Deno. I'm not knowledgeable about how Deno.build.os is set, so I could be wrong, however.

2020-12-07 15:30 UTC, bartlomieju commented
@MVEMCJSUNPE what do you mean by cross compiling Deno? I don't think there's an option to do that currently. Also `Deno.build` uses LLVM target triples for its values.

2020-12-07 18:23 UTC, MVEMCJSUNPE commented
Oh nvm then. So should I use Deno.build.os to implement os.type polyfill?

2020-12-07 18:25 UTC, bartlomieju commented
> Oh nvm then. So should I use Deno.build.os to implement os.type polyfill?

@MVEMCJSUNPE yes, that would be preferable solution

2020-12-09 23:13 UTC, MVEMCJSUNPE commented
For some reason, the test for Mac OS X is failing.

2020-12-12 13:31 UTC, bartlomieju commented
> For some reason, the check for Mac OS X is failing.

Looks like one-off failure.

2020-12-12 13:32 UTC, bartlomieju requested changes

2020-12-12 13:32 UTC, bartlomieju commented on cli/rt/30_os.js
> +  }
Remove

2020-12-12 13:32 UTC, bartlomieju commented on cli/rt/30_os.js
> +    osType,
Remove

2020-12-15 10:12 UTC, ry approved these changes
LGTM - thanks @MVEMCJSUNPE

2020-12-15 10:13 UTC, merged