feat(doc): Add the documentation for addEventListener Method
denoland/deno pull request #8811
Opened 2020-12-17 22:24 UTC by championshuttler

Fixes #8804

2020-12-17 22:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno?pullRequest=8811) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno?pullRequest=8811) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno?pullRequest=8811) it.</sub>

2020-12-18 04:25 UTC, kitsonk requested changes

2020-12-18 04:25 UTC, kitsonk commented on op_crates/web/lib.deno_web.d.ts
> +  /** addEventListener() method attaches an event handler to the document.
This should be a continuation of the previous JSDoc block, just adding the example, with a clean line break before it.

2020-12-18 18:23 UTC, ry commented
Thank you but the issue is actually denoland/deno_doc#31

2020-12-18 18:23 UTC, closed without merging