[WIP] CLI features don't require --unstable
denoland/deno pull request #8938
Opened 2020-12-30 16:56 UTC by bartlomieju

2020-12-31 03:39 UTC, kitsonk approved these changes
LGTM

2020-12-31 11:16 UTC, ry commented
I'm a little worried about `--import-map`  and `deno test --no-run` (what is its purpose anyway?)

2020-12-31 11:25 UTC, lucacasonato approved these changes
There is no distinction that import maps are still unstable now. We either need a new flag for CLI unstable, or add a yellow warning output if this flag is used.

2020-12-31 11:27 UTC, lucacasonato requested changes
That was meant to be a request changes. 🤦‍♂️

2020-12-31 11:39 UTC, bartlomieju commented
> I'm a little worried about `--import-map` and `deno test --no-run` (what is its purpose anyway?)

`deno test --no-run` collects, caches and type checks all files that will be tested (but doesn't actually run the tests).

> We either need a new flag for CLI unstable, or add a yellow warning output if this flag is used.

Showing a warning is fair, I'd rather not introduce another CLI flag, that's the whole purpose of this PR. I'll update to show the warning.

2020-12-31 17:05 UTC, nayeemrmn requested changes
Since there's no longer an enforced flag requirement, it should consistently say `Unstable: ` in the help messages of unstable flags and subcommands.

2020-12-31 17:05 UTC, nayeemrmn commented on cli/flags.rs
> +      "Load import map file
It should still say "unstable" or similar in the help message.

2020-12-31 17:05 UTC, nayeemrmn commented on cli/flags.rs
>          .help("Cache test modules, but don't run tests")
Ditto. Especially now since there is no longer a flag requirement.

2021-01-17 16:32 UTC, lucacasonato commented
@bartlomieju changed his mind. Closing

2021-01-17 16:32 UTC, closed without merging