Feature: coverage threshold
denoland/deno pull request #9826
Opened 2021-03-18 15:16 UTC by ayshiff

Closes #9669

This PR adds the possibility to set a threshold to the `deno coverage` command and fail if coverage doesn't meet it.

I have reused the same nomenclature that was proposed in the issue.

![carbon (10)](https://user-images.githubusercontent.com/32459935/111647298-a84f1800-8802-11eb-9aba-e4d0a8b278e1.png)

If the command has the `--lcov` flag, it will check the coverage for `lines`, `branches` and `functions` otherwise it will only check for `lines` as the `PrettyCoverageReporter` doesn't have a way to identify the coverage for `branches` and `functions`.

By default, the threshold is set to **80%**.

If coverage doesn't meet the threshold, it will throw an error and display the coverage elements that are below the threshold.

<p align="center">
<img src="https://user-images.githubusercontent.com/32459935/111647969-39be8a00-8803-11eb-8d36-66e1ba49f763.png" width="600" />
</p>

I would love to get your feedback on what I did and discuss what could be improved 👍

I don't know if the `println` errors are relevant, in case the user does a `deno coverage --unstable cov_profile --lcov > cov_profile.lcov`. He will get the errors `"The coverage threshold..."` in his file.

2021-03-18 15:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/denoland/deno?pullRequest=9826) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/denoland/deno?pullRequest=9826) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/denoland/deno?pullRequest=9826) it.</sub>

2021-03-18 23:11 UTC, caspervonb commented on cli/tools/coverage.rs
> +    if !threshold_met {
Exit early.

2021-03-18 23:12 UTC, caspervonb commented on cli/tools/coverage.rs
> +    let total_coverage = reporter.visit_coverage(
Reporter shouldn't return anything, adds even more duplication.

2021-03-18 23:14 UTC, caspervonb commented on cli/tools/coverage.rs
> +    let total_coverage = reporter.visit_coverage(
Also check shouldn't have any relationship with the reporter.

2021-03-18 23:16 UTC, caspervonb requested changes
This approach is too tightly coupled to the reporter, check should be independent of the output format.

2021-03-19 08:39 UTC, ayshiff commented
> Hi there!
> 
> Thanks for attempting this but would perhaps be better if you checked in before, already have a draft for this am just busy with a different feature at the moment.
> 
> This approach is too tightly coupled to the reporter, check should be independent of the output format.

Okay, no problem!
Sorry, I hadn't seen the draft and since the issue didn't mention anything I didn't pay attention.
I can't find the draft, can you point it out to me, I'd love to see the right way to implement this feature.
Thanks

2021-03-19 09:00 UTC, crypt096 approved these changes

2021-05-03 14:49 UTC, bartlomieju commented
@ayshiff thank you for the PR! I've discussed it out of bands with @caspervonb and while we appreciate the effort we think it's not the right approach (especially with recent changes to the test runner infrastructure). Casper said he'll revisit the topic in the near future. Closing without a merge.

2021-05-03 14:49 UTC, closed without merging